# Task 3 — Neural Machine Translation

1. Load the aligned and preprocessed sentence pairs produced in Task 2.
2. Split the data into training, validation, and test sets, reserving 20% for testing.
3. Develop an RNN-based encoder–decoder model for English-to-Italian translation.
4. Tune a small number of relevant hyperparameters using validation performance.
5. Evaluate the generated translations using BLEU and METEOR.
6. Reverse the translation direction and train an Italian-to-English model.
7. Develop a character-based model and compare it with the word-based models.

In [1]:
%pip install -q nltk gensim

from google.colab import drive

drive.mount("/content/drive")

!nvidia-smi

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 30.9 MB/s eta 0:00:00
Mounted at /content/drive
Sun Jul 26 20:25:03 2026
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   46C    P8             10W /   70W |       0MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+------------------------+----------------------+

+-----------------------------------------------------------------------------------------+
| Processes:                                                                              |
|  GPU   GI   CI              PID   Type   Process name                        GPU Memory |
|        ID   ID                                                               Usage      |
|=========================================================================================|
|  No running processes found                                                             |
+-----------------------------------------------------------------------------------------+

## Evaluation metrics

BLEU and METEOR are used throughout.

In [ ]:
from pathlib import Path
import random
import re

import numpy as np
import torch

SEED = 42

random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

if not torch.cuda.is_available():
    raise RuntimeError(
        "CUDA is not available. Select a GPU runtime in Colab."
    )

DEVICE = torch.device("cuda")
torch.cuda.manual_seed_all(SEED)

torch.backends.cudnn.deterministic = True
torch.backends.cudnn.benchmark = False

PROJECT_ROOT = Path(
    "/content/drive/MyDrive/English-Italian-Machine-Translation-"
)

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"

EN_PATH = PROCESSED_DIR / "task2_clean.en"
IT_PATH = PROCESSED_DIR / "task2_clean.it"

print(EN_PATH.exists())
print(IT_PATH.exists())

RUN_NAME = "gpu_punctuation_final"

MODEL_DIR = (
    PROJECT_ROOT
    / "models"
    / "task3"
    / RUN_NAME
)

RESULTS_DIR = (
    PROJECT_ROOT
    / "results"
    / "task3_outputs"
    / RUN_NAME
)

MODEL_DIR.mkdir(parents=True, exist_ok=True)
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

if not EN_PATH.exists() or not IT_PATH.exists():
    raise FileNotFoundError(
        "Task 2 outputs not found."
    )

print(f"Device: {DEVICE}")
print(f"GPU: {torch.cuda.get_device_name(0)}")
print(f"Project root: {PROJECT_ROOT}")
print(f"Models: {MODEL_DIR}")
print(f"Results: {RESULTS_DIR}")

True
True
Device: cuda
GPU: Tesla T4
Project root: /content/drive/MyDrive/English-Italian-Machine-Translation-
Models: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final
Results: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final

## 1. Data loading and splitting

In [ ]:
def read_lines(path):
    """Read a text file and return one sentence per line."""
    with path.open("r", encoding="utf-8") as file:
        return [line.rstrip("\n") for line in file]


english_sentences = read_lines(EN_PATH)
italian_sentences = read_lines(IT_PATH)

assert len(english_sentences) == len(italian_sentences), (
    "The English and Italian files are not aligned."
)

TOKEN_PATTERN = re.compile(
    r"\d+(?:[.,]\d+)*|\w+(?:['’]\w+)*|[^\w\s]",
    flags=re.UNICODE,
)

def tokenize(sentence):
    """Separate punctuation while preserving contractions and decimal numbers."""
    return TOKEN_PATTERN.findall(sentence)

sentence_pairs = list(zip(english_sentences, italian_sentences))

print(f"Aligned sentence pairs: {len(sentence_pairs):,}")

for i, (english, italian) in enumerate(sentence_pairs[:3], start=1):
    print(f"\nExample {i}")
    print(f"EN: {english}")
    print(f"IT: {italian}")

Aligned sentence pairs: 190,110

Example 1
EN: madam president, on a point of order.
IT: signora presidente, un richiamo al regolamento.

Example 2
EN: madam president, coinciding with this year' s first part-session of the european parliament, a date has been set, unfortunately for next thursday, in texas in america, for the execution of a young 34 year-old man who has been sentenced to death. we shall call him mr hicks.
IT: signora presidente, in coincidenza con la prima tornata dell'anno del parlamento europeo, negli stati uniti in texas è stata fissata, purtroppo per giovedì prossimo, l'esecuzione di un condannato a morte, un giovane di 34 anni che chiameremo di nome hicks.

Example 3
EN: madam president, i would firstly like to compliment you on the fact that you have kept your word and that, during this first part-session of the new year, the number of television channels in our offices has indeed increased considerably.
IT: signora presidente, mi permetta di farle innanzi tutto i miei complimenti per aver tenuto fede alla parola data. in effetti il numero di canali televisivi disponibili nei nostri uffici è aumentato enormemente in questa prima tornata dell'anno nuovo.

In [4]:
TEST_RATIO = 0.20
VALIDATION_RATIO = 0.10
MAX_SENTENCE_LENGTH = 40


def count_whitespace_words(sentence):
    """Count whitespace-delimited words for computational filtering."""
    return len(sentence.split())


sentence_pairs = [
    (english, italian)
    for english, italian in sentence_pairs
    if count_whitespace_words(english) <= MAX_SENTENCE_LENGTH
    and count_whitespace_words(italian) <= MAX_SENTENCE_LENGTH
]

print(f"Pairs after length filtering: {len(sentence_pairs):,}")

number_of_pairs = len(sentence_pairs)

number_of_test_pairs = int(number_of_pairs * TEST_RATIO)
number_of_validation_pairs = int(number_of_pairs * VALIDATION_RATIO)
number_of_training_pairs = (
    number_of_pairs
    - number_of_validation_pairs
    - number_of_test_pairs
)

rng = np.random.default_rng(SEED)
shuffled_indices = rng.permutation(number_of_pairs)

training_indices = shuffled_indices[:number_of_training_pairs]
validation_indices = shuffled_indices[
    number_of_training_pairs:
    number_of_training_pairs + number_of_validation_pairs
]
test_indices = shuffled_indices[
    number_of_training_pairs + number_of_validation_pairs:
]

training_pairs = [sentence_pairs[i] for i in training_indices]
validation_pairs = [sentence_pairs[i] for i in validation_indices]
test_pairs = [sentence_pairs[i] for i in test_indices]

print(f"Training pairs:   {len(training_pairs):,} ({len(training_pairs) / number_of_pairs:.1%})")
print(f"Validation pairs: {len(validation_pairs):,} ({len(validation_pairs) / number_of_pairs:.1%})")
print(f"Test pairs:       {len(test_pairs):,} ({len(test_pairs) / number_of_pairs:.1%})")

Pairs after length filtering: 157,519
Training pairs:   110,265 (70.0%)
Validation pairs: 15,751 (10.0%)
Test pairs:       31,503 (20.0%)

## 2. Word-level data preparation

In [ ]:
from collections import Counter


MAX_VOCABULARY_SIZE = 20_000

SPECIAL_TOKENS = ["<pad>", "<unk>", "<sos>", "<eos>"]
PAD_INDEX, UNK_INDEX, SOS_INDEX, EOS_INDEX = range(len(SPECIAL_TOKENS))

def build_vocabulary(sentences, max_size=MAX_VOCABULARY_SIZE):
    """Build a vocabulary from the most frequent training words."""
    word_counts = Counter(
        word
        for sentence in sentences
        for word in tokenize(sentence)
    )

    words = [
        word
        for word, _ in word_counts.most_common(
            max_size - len(SPECIAL_TOKENS)
        )
    ]

    index_to_token = SPECIAL_TOKENS + words
    token_to_index = {
        token: index
        for index, token in enumerate(index_to_token)
    }

    return token_to_index, index_to_token


english_training_sentences = [
    english for english, _ in training_pairs
]
italian_training_sentences = [
    italian for _, italian in training_pairs
]

english_token_to_index, english_index_to_token = build_vocabulary(
    english_training_sentences
)
italian_token_to_index, italian_index_to_token = build_vocabulary(
    italian_training_sentences
)

print(f"English vocabulary: {len(english_token_to_index):,} tokens")
print(f"Italian vocabulary: {len(italian_token_to_index):,} tokens")

English vocabulary: 20,000 tokens
Italian vocabulary: 20,000 tokens

In [6]:
from torch.nn.utils.rnn import pad_sequence
from torch.utils.data import Dataset, DataLoader


BATCH_SIZE = 128


def encode_sentence(sentence, token_to_index):
    """Convert a sentence into token indices."""
    word_indices = [
        token_to_index.get(word, UNK_INDEX)
        for word in tokenize(sentence)
    ]

    return torch.tensor(
        [SOS_INDEX] + word_indices + [EOS_INDEX],
        dtype=torch.long,
    )


class TranslationDataset(Dataset):
    """Store aligned source and target sentences."""

    def __init__(self, pairs, source_vocabulary, target_vocabulary):
        self.pairs = pairs
        self.source_vocabulary = source_vocabulary
        self.target_vocabulary = target_vocabulary

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):
        source_sentence, target_sentence = self.pairs[index]

        source = encode_sentence(
            source_sentence,
            self.source_vocabulary,
        )
        target = encode_sentence(
            target_sentence,
            self.target_vocabulary,
        )

        return source, target


def collate_batch(batch):
    """Pad the source and target sequences in one batch."""
    sources, targets = zip(*batch)

    source_lengths = torch.tensor(
        [len(source) for source in sources],
        dtype=torch.long,
    )

    padded_sources = pad_sequence(
        sources,
        batch_first=True,
        padding_value=PAD_INDEX,
    )
    padded_targets = pad_sequence(
        targets,
        batch_first=True,
        padding_value=PAD_INDEX,
    )

    return padded_sources, source_lengths, padded_targets


training_dataset = TranslationDataset(
    training_pairs,
    english_token_to_index,
    italian_token_to_index,
)
validation_dataset = TranslationDataset(
    validation_pairs,
    english_token_to_index,
    italian_token_to_index,
)
test_dataset = TranslationDataset(
    test_pairs,
    english_token_to_index,
    italian_token_to_index,
)

data_generator = torch.Generator().manual_seed(SEED)

training_loader = DataLoader(
    training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=data_generator,
)
validation_loader = DataLoader(
    validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)
test_loader = DataLoader(
    test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)


source_batch, source_lengths, target_batch = next(iter(training_loader))

print(f"Training examples: {len(training_dataset):,}")
print(f"Validation examples: {len(validation_dataset):,}")
print(f"Test examples: {len(test_dataset):,}")
print(f"Source batch shape: {source_batch.shape}")
print(f"Target batch shape: {target_batch.shape}")
print(f"First source lengths: {source_lengths[:5].tolist()}")

Training examples: 110,265
Validation examples: 15,751
Test examples: 31,503
Source batch shape: torch.Size([128, 47])
Target batch shape: torch.Size([128, 47])
First source lengths: [18, 18, 9, 37, 21]

## 3. RNN encoder–decoder

In [ ]:
from torch import nn
from torch.nn.utils.rnn import pack_padded_sequence


EMBEDDING_DIMENSION = 64
HIDDEN_DIMENSION = 128


class Encoder(nn.Module):
    """Encode a source sentence into its final hidden state."""

    def __init__(self, vocabulary_size, embedding_dimension, hidden_dimension):
        super().__init__()

        self.embedding = nn.Embedding(
            vocabulary_size,
            embedding_dimension,
            padding_idx=PAD_INDEX,
        )
        self.rnn = nn.RNN(
            embedding_dimension,
            hidden_dimension,
            batch_first=True,
            nonlinearity="tanh",
        )

    def forward(self, source, source_lengths):
        embedded = self.embedding(source)

        packed = pack_padded_sequence(
            embedded,
            source_lengths.cpu(),
            batch_first=True,
            enforce_sorted=False,
        )

        _, hidden = self.rnn(packed)

        return hidden


class Decoder(nn.Module):
    """Generate target-word scores using the fixed encoder context."""

    def __init__(
        self,
        vocabulary_size,
        embedding_dimension,
        hidden_dimension,
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocabulary_size,
            embedding_dimension,
            padding_idx=PAD_INDEX,
        )

        self.rnn = nn.RNN(
            embedding_dimension + hidden_dimension,
            hidden_dimension,
            batch_first=True,
            nonlinearity="tanh",
        )

        self.output_layer = nn.Linear(
            hidden_dimension,
            vocabulary_size,
        )

    def forward(self, target_input, hidden, context):
        embedded = self.embedding(target_input)

        repeated_context = context[-1].unsqueeze(1).expand(
            -1,
            target_input.size(1),
            -1,
        )

        decoder_input = torch.cat(
            [embedded, repeated_context],
            dim=-1,
        )

        output, hidden = self.rnn(decoder_input, hidden)
        logits = self.output_layer(output)

        return logits, hidden


class Seq2Seq(nn.Module):
    """Combine the encoder and the context-fed decoder."""

    def __init__(self, encoder, decoder):
        super().__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, source, source_lengths, target_input):
        context = self.encoder(source, source_lengths)
        hidden = context

        logits, _ = self.decoder(
            target_input,
            hidden,
            context,
        )

        return logits


encoder = Encoder(
    vocabulary_size=len(english_token_to_index),
    embedding_dimension=EMBEDDING_DIMENSION,
    hidden_dimension=HIDDEN_DIMENSION,
)

decoder = Decoder(
    vocabulary_size=len(italian_token_to_index),
    embedding_dimension=EMBEDDING_DIMENSION,
    hidden_dimension=HIDDEN_DIMENSION,
)

model = Seq2Seq(encoder, decoder).to(DEVICE)


# Check the model output dimensions using one small batch.
example_source = source_batch[:4].to(DEVICE)
example_lengths = source_lengths[:4]
example_target_input = target_batch[:4, :-1].to(DEVICE)

with torch.no_grad():
    example_logits = model(
        example_source,
        example_lengths,
        example_target_input,
    )

expected_shape = (
    example_target_input.size(0),
    example_target_input.size(1),
    len(italian_token_to_index),
)

assert example_logits.shape == expected_shape

number_of_parameters = sum(
    parameter.numel()
    for parameter in model.parameters()
)

print(model)
print(f"\nOutput shape: {example_logits.shape}")
print(f"Trainable parameters: {number_of_parameters:,}")

assert next(model.parameters()).is_cuda

Seq2Seq(
  (encoder): Encoder(
    (embedding): Embedding(20000, 64, padding_idx=0)
    (rnn): RNN(64, 128, batch_first=True)
  )
  (decoder): Decoder(
    (embedding): Embedding(20000, 64, padding_idx=0)
    (rnn): RNN(192, 128, batch_first=True)
    (output_layer): Linear(in_features=128, out_features=20000, bias=True)
  )
)

Output shape: torch.Size([4, 46, 20000])
Trainable parameters: 5,206,048
Model device: cuda:0

## 4. Training and evaluation strategy

In [8]:
MAX_GRADIENT_NORM = 1.0


def train_one_epoch(model, data_loader, optimizer, loss_function):
    """Train the model for one epoch and return the mean token loss."""
    model.train()

    total_loss = 0.0
    total_tokens = 0

    for source, source_lengths, target in data_loader:
        source = source.to(DEVICE)
        target = target.to(DEVICE)

        target_input = target[:, :-1]
        target_output = target[:, 1:]

        optimizer.zero_grad()

        logits = model(source, source_lengths, target_input)

        loss = loss_function(
            logits.reshape(-1, logits.size(-1)),
            target_output.reshape(-1),
        )

        loss.backward()

        nn.utils.clip_grad_norm_(
            model.parameters(),
            MAX_GRADIENT_NORM,
        )

        optimizer.step()

        number_of_tokens = (
            target_output != PAD_INDEX
        ).sum().item()

        total_loss += loss.item() * number_of_tokens
        total_tokens += number_of_tokens

    return total_loss / total_tokens


@torch.no_grad()
def validate_one_epoch(model, data_loader, loss_function):
    """Evaluate the model and return the mean token loss."""
    model.eval()

    total_loss = 0.0
    total_tokens = 0

    for source, source_lengths, target in data_loader:
        source = source.to(DEVICE)
        target = target.to(DEVICE)

        target_input = target[:, :-1]
        target_output = target[:, 1:]

        logits = model(source, source_lengths, target_input)

        loss = loss_function(
            logits.reshape(-1, logits.size(-1)),
            target_output.reshape(-1),
        )

        number_of_tokens = (
            target_output != PAD_INDEX
        ).sum().item()

        total_loss += loss.item() * number_of_tokens
        total_tokens += number_of_tokens

    return total_loss / total_tokens

In [ ]:
try:
    from nltk.stem import SnowballStemmer
    from nltk.translate.bleu_score import corpus_bleu, SmoothingFunction
    from nltk.translate.meteor_score import meteor_score
except ImportError as error:
    raise ImportError(
        "NLTK is required"
    ) from error


MAX_DECODE_LENGTH = 80

class NoSynonyms:
    """Disable WordNet synonym matching in METEOR."""

    @staticmethod
    def synsets(word):
        return []


def indices_to_tokens(indices, index_to_token):
    """Convert generated indices into tokens."""
    tokens = []

    for index in indices:
        index = int(index)

        if index == EOS_INDEX:
            break

        if index not in (PAD_INDEX, SOS_INDEX):
            tokens.append(index_to_token[index])

    return tokens


@torch.no_grad()
def generate_translations(model, data_loader, target_index_to_token):
    """Generate translations for a complete DataLoader."""
    model.eval()

    hypotheses = []

    for source, source_lengths, _ in data_loader:
        source = source.to(DEVICE)

        context = model.encoder(source, source_lengths)
        hidden = context

        current_token = torch.full(
            (source.size(0), 1),
            SOS_INDEX,
            dtype=torch.long,
            device=DEVICE,
        )

        generated_tokens = []
        finished = torch.zeros(
            source.size(0),
            dtype=torch.bool,
            device=DEVICE,
        )

        for _ in range(MAX_DECODE_LENGTH):
            logits, hidden = model.decoder(
                current_token,
                hidden,
                context,
            )
            step_logits = logits[:, -1].clone()

            step_logits[
                :,
                [PAD_INDEX, UNK_INDEX, SOS_INDEX],
            ] = float("-inf")

            next_token = step_logits.argmax(dim=-1)

            next_token = torch.where(
                finished,
                torch.full_like(next_token, EOS_INDEX),
                next_token,
            )

            generated_tokens.append(next_token.cpu())
            finished |= next_token.eq(EOS_INDEX)
            current_token = next_token.unsqueeze(1)

            if finished.all():
                break

        generated_tokens = torch.stack(
            generated_tokens,
            dim=1,
        )

        hypotheses.extend(
            indices_to_tokens(sequence, target_index_to_token)
            for sequence in generated_tokens
        )

    references = [
        tokenize(target_sentence)
        for _, target_sentence in data_loader.dataset.pairs
    ]

    assert len(references) == len(hypotheses)

    return references, hypotheses

def compute_translation_metrics(
    references,
    hypotheses,
    target_language,
):
    """Compute corpus BLEU and mean sentence METEOR."""
    bleu = 100 * corpus_bleu(
        [[reference] for reference in references],
        hypotheses,
        smoothing_function=SmoothingFunction().method1,
    )
    
    stemmer = SnowballStemmer(target_language)
    no_synonyms = NoSynonyms()

    meteor_values = [
        meteor_score(
            [reference],
            hypothesis,
            stemmer=stemmer,
            wordnet=no_synonyms,
        )
        for reference, hypothesis in zip(references, hypotheses)
    ]

    meteor = 100 * sum(meteor_values) / len(meteor_values)

    return {
        "BLEU": bleu,
        "METEOR": meteor,
    }

In [10]:
import time


def run_experiment(
    model,
    training_loader,
    validation_loader,
    checkpoint_name,
    number_of_epochs=20,
    learning_rate=0.001,
    early_stopping_patience=3,
):
    """Train a model, apply early stopping and restore the best checkpoint."""

    loss_function = nn.CrossEntropyLoss(
        ignore_index=PAD_INDEX,
    )

    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=learning_rate,
    )

    checkpoint_path = MODEL_DIR / checkpoint_name

    best_validation_loss = float("inf")
    best_epoch = 0
    epochs_without_improvement = 0
    stopped_early = False

    history = {
        "training_loss": [],
        "validation_loss": [],
    }

    start_time = time.perf_counter()

    for epoch in range(1, number_of_epochs + 1):
        training_loss = train_one_epoch(
            model,
            training_loader,
            optimizer,
            loss_function,
        )

        validation_loss = validate_one_epoch(
            model,
            validation_loader,
            loss_function,
        )

        history["training_loss"].append(training_loss)
        history["validation_loss"].append(validation_loss)

        if validation_loss < best_validation_loss:
            best_validation_loss = validation_loss
            best_epoch = epoch
            epochs_without_improvement = 0

            torch.save(
                model.state_dict(),
                checkpoint_path,
            )
        else:
            epochs_without_improvement += 1

        print(
            f"Epoch {epoch}/{number_of_epochs} | "
            f"training loss: {training_loss:.4f} | "
            f"validation loss: {validation_loss:.4f}"
        )

        if (
            early_stopping_patience is not None
            and epochs_without_improvement
            >= early_stopping_patience
        ):
            stopped_early = True

            print(
                "Early stopping: validation loss did not "
                f"improve for {early_stopping_patience} epochs."
            )
            break

    elapsed_seconds = time.perf_counter() - start_time

    model.load_state_dict(
        torch.load(
            checkpoint_path,
            map_location=DEVICE,
        )
    )

    history["elapsed_seconds"] = elapsed_seconds
    history["best_validation_loss"] = best_validation_loss
    history["best_epoch"] = best_epoch
    history["epochs_completed"] = len(
        history["training_loss"]
    )
    history["stopped_early"] = stopped_early

    print(f"Best epoch: {best_epoch}")
    print(f"Best validation loss: {best_validation_loss:.4f}")
    print(
        f"Training time: "
        f"{elapsed_seconds / 60:.2f} minutes"
    )
    print(f"Checkpoint: {checkpoint_path}")

    return history

## 5. hyperparameter tuning

In [ ]:
TUNING_TRAINING_SIZE = len(training_pairs)
TUNING_VALIDATION_SIZE = len(validation_pairs)

tuning_training_pairs = training_pairs
tuning_validation_pairs = validation_pairs

TUNING_EPOCHS = 15

tuning_training_dataset = TranslationDataset(
    tuning_training_pairs,
    english_token_to_index,
    italian_token_to_index,
)
tuning_validation_dataset = TranslationDataset(
    tuning_validation_pairs,
    english_token_to_index,
    italian_token_to_index,
)

tuning_validation_loader = DataLoader(
    tuning_validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)


def create_model(
    source_vocabulary_size,
    target_vocabulary_size,
    embedding_dimension,
    hidden_dimension,
):
    """Create a new RNN encoder-decoder model."""
    encoder = Encoder(
        source_vocabulary_size,
        embedding_dimension,
        hidden_dimension,
    )
    decoder = Decoder(
        target_vocabulary_size,
        embedding_dimension,
        hidden_dimension,
    )

    return Seq2Seq(encoder, decoder).to(DEVICE)


tuning_configurations = [
    {
        "name": "small",
        "embedding_dimension": 64,
        "hidden_dimension": 64,
        "learning_rate": 0.001,
    },
    {
        "name": "medium",
        "embedding_dimension": 64,
        "hidden_dimension": 128,
        "learning_rate": 0.001,
    },
    {
        "name": "lower_learning_rate",
        "embedding_dimension": 64,
        "hidden_dimension": 128,
        "learning_rate": 0.0005,
    },
]

tuning_results = []

for configuration in tuning_configurations:
    print(f"\nConfiguration: {configuration['name']}")

    # Use the same initialization and training order for each run.
    torch.manual_seed(SEED)

    tuning_training_loader = DataLoader(
        tuning_training_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=collate_batch,
        generator=torch.Generator().manual_seed(SEED),
    )

    tuning_model = create_model(
        source_vocabulary_size=len(english_token_to_index),
        target_vocabulary_size=len(italian_token_to_index),
        embedding_dimension=configuration["embedding_dimension"],
        hidden_dimension=configuration["hidden_dimension"],
    )

    history = run_experiment(
        model=tuning_model,
        training_loader=tuning_training_loader,
        validation_loader=tuning_validation_loader,
        checkpoint_name=f"tuning_{configuration['name']}.pt",
        number_of_epochs=TUNING_EPOCHS,
        learning_rate=configuration["learning_rate"],
    )

    references, hypotheses = generate_translations(
        tuning_model,
        tuning_validation_loader,
        italian_index_to_token,
    )
    metrics = compute_translation_metrics(
        references,
        hypotheses,
        target_language="italian",
    )

    best_epoch_index = int(
        np.argmin(history["validation_loss"])
    )

    number_of_parameters = sum(
        parameter.numel()
        for parameter in tuning_model.parameters()
    )

    tuning_results.append(
        {
            **configuration,
            "best_epoch": best_epoch_index + 1,
            "training_loss": history["training_loss"][best_epoch_index],
            "validation_loss": history["validation_loss"][best_epoch_index],
            "BLEU": metrics["BLEU"],
            "METEOR": metrics["METEOR"],
            "parameters": number_of_parameters,
            "training_minutes": history["elapsed_seconds"] / 60,
        }
    )

    print(f"Validation BLEU: {metrics['BLEU']:.2f}")
    print(f"Validation METEOR: {metrics['METEOR']:.2f}")

Configuration: small
Epoch 1/15 | training loss: 6.2471 | validation loss: 5.5100
Epoch 2/15 | training loss: 5.2871 | validation loss: 5.0714
Epoch 3/15 | training loss: 4.9714 | validation loss: 4.8719
Epoch 4/15 | training loss: 4.7955 | validation loss: 4.7552
Epoch 5/15 | training loss: 4.6798 | validation loss: 4.6800
Epoch 6/15 | training loss: 4.5951 | validation loss: 4.6267
Epoch 7/15 | training loss: 4.5292 | validation loss: 4.5845
Epoch 8/15 | training loss: 4.4758 | validation loss: 4.5534
Epoch 9/15 | training loss: 4.4311 | validation loss: 4.5276
Epoch 10/15 | training loss: 4.3927 | validation loss: 4.5070
Epoch 11/15 | training loss: 4.3594 | validation loss: 4.4908
Epoch 12/15 | training loss: 4.3294 | validation loss: 4.4747
Epoch 13/15 | training loss: 4.3024 | validation loss: 4.4645
Epoch 14/15 | training loss: 4.2779 | validation loss: 4.4514
Epoch 15/15 | training loss: 4.2557 | validation loss: 4.4439
Best epoch: 15
Best validation loss: 4.4439
Training time: 11.42 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/tuning_small.pt
Validation BLEU: 0.96
Validation METEOR: 10.68

Configuration: medium
Epoch 1/15 | training loss: 6.0029 | validation loss: 5.2778
Epoch 2/15 | training loss: 5.0444 | validation loss: 4.8321
Epoch 3/15 | training loss: 4.7150 | validation loss: 4.6403
Epoch 4/15 | training loss: 4.5343 | validation loss: 4.5319
Epoch 5/15 | training loss: 4.4135 | validation loss: 4.4635
Epoch 6/15 | training loss: 4.3250 | validation loss: 4.4198
Epoch 7/15 | training loss: 4.2543 | validation loss: 4.3844
Epoch 8/15 | training loss: 4.1955 | validation loss: 4.3599
Epoch 9/15 | training loss: 4.1466 | validation loss: 4.3462
Epoch 10/15 | training loss: 4.1025 | validation loss: 4.3228
Epoch 11/15 | training loss: 4.0647 | validation loss: 4.3151
Epoch 12/15 | training loss: 4.0290 | validation loss: 4.3030
Epoch 13/15 | training loss: 3.9988 | validation loss: 4.3042
Epoch 14/15 | training loss: 3.9674 | validation loss: 4.2986
Epoch 15/15 | training loss: 3.9403 | validation loss: 4.2874
Best epoch: 15
Best validation loss: 4.2874
Training time: 13.16 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/tuning_medium.pt
Validation BLEU: 1.87
Validation METEOR: 13.26

Configuration: lower_learning_rate
Epoch 1/15 | training loss: 6.3634 | validation loss: 5.6800
Epoch 2/15 | training loss: 5.4035 | validation loss: 5.1473
Epoch 3/15 | training loss: 5.0343 | validation loss: 4.9137
Epoch 4/15 | training loss: 4.8300 | validation loss: 4.7729
Epoch 5/15 | training loss: 4.6950 | validation loss: 4.6780
Epoch 6/15 | training loss: 4.5940 | validation loss: 4.6050
Epoch 7/15 | training loss: 4.5127 | validation loss: 4.5565
Epoch 8/15 | training loss: 4.4464 | validation loss: 4.5107
Epoch 9/15 | training loss: 4.3900 | validation loss: 4.4736
Epoch 10/15 | training loss: 4.3393 | validation loss: 4.4426
Epoch 11/15 | training loss: 4.2950 | validation loss: 4.4198
Epoch 12/15 | training loss: 4.2553 | validation loss: 4.3963
Epoch 13/15 | training loss: 4.2197 | validation loss: 4.3764
Epoch 14/15 | training loss: 4.1868 | validation loss: 4.3636
Epoch 15/15 | training loss: 4.1574 | validation loss: 4.3462
Best epoch: 15
Best validation loss: 4.3462
Training time: 13.23 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/tuning_lower_learning_rate.pt
Validation BLEU: 1.76
Validation METEOR: 13.38

In [ ]:
import pandas as pd
from IPython.display import display


tuning_results_table = pd.DataFrame(tuning_results)

tuning_results_table = tuning_results_table[
    [
        "name",
        "embedding_dimension",
        "hidden_dimension",
        "learning_rate",
        "best_epoch",
        "training_loss",
        "validation_loss",
        "BLEU",
        "METEOR",
        "parameters",
        "training_minutes",
    ]
].sort_values("validation_loss")

display(
    tuning_results_table.round(
        {
            "training_loss": 4,
            "validation_loss": 4,
            "BLEU": 2,
            "METEOR": 2,
            "training_minutes": 2,
        }
    )
)

best_configuration = min(
    tuning_results,
    key=lambda result: result["validation_loss"],
)

BEST_EMBEDDING_DIMENSION = best_configuration[
    "embedding_dimension"
]
BEST_HIDDEN_DIMENSION = best_configuration[
    "hidden_dimension"
]
BEST_LEARNING_RATE = best_configuration[
    "learning_rate"
]
FINAL_NUMBER_OF_EPOCHS = 30

tuning_results_path = (
    RESULTS_DIR / "hyperparameter_tuning_results.csv"
)
tuning_results_table.to_csv(
    tuning_results_path,
    index=False,
)

print(f"Selected configuration: {best_configuration['name']}")
print(f"Embedding dimension: {BEST_EMBEDDING_DIMENSION}")
print(f"Hidden dimension: {BEST_HIDDEN_DIMENSION}")
print(f"Learning rate: {BEST_LEARNING_RATE}")
print(f"Saved results: {tuning_results_path}")

,name,embedding_dimension,hidden_dimension,learning_rate,best_epoch,training_loss,validation_loss,BLEU,METEOR,parameters,training_minutes
1,medium,64,128,0.0010,15,3.9403,4.2874,1.87,13.26,5206048,13.16
2,lower_learning_rate,64,128,0.0005,15,4.1574,4.3462,1.76,13.38,5206048,13.23
0,small,64,64,0.0010,15,4.2557,4.4439,0.96,10.68,3880736,11.42

Selected configuration: medium
Embedding dimension: 64
Hidden dimension: 128
Learning rate: 0.001
Saved results: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/hyperparameter_tuning_results.csv

## 6. English-to-Italian experiments

In [ ]:
FINAL_NUMBER_OF_EPOCHS = 20

final_training_loader = DataLoader(
    training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)

torch.manual_seed(SEED)

english_to_italian_model = create_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=BEST_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_HIDDEN_DIMENSION,
)

english_to_italian_history = run_experiment(
    model=english_to_italian_model,
    training_loader=final_training_loader,
    validation_loader=validation_loader,
    checkpoint_name="english_to_italian_word_rnn.pt",
    number_of_epochs=FINAL_NUMBER_OF_EPOCHS,
    learning_rate=BEST_LEARNING_RATE,
)

Epoch 1/20 | training loss: 6.0029 | validation loss: 5.2778
Epoch 2/20 | training loss: 5.0444 | validation loss: 4.8321
Epoch 3/20 | training loss: 4.7150 | validation loss: 4.6403
Epoch 4/20 | training loss: 4.5343 | validation loss: 4.5319
Epoch 5/20 | training loss: 4.4135 | validation loss: 4.4635
Epoch 6/20 | training loss: 4.3250 | validation loss: 4.4198
Epoch 7/20 | training loss: 4.2543 | validation loss: 4.3844
Epoch 8/20 | training loss: 4.1955 | validation loss: 4.3599
Epoch 9/20 | training loss: 4.1466 | validation loss: 4.3462
Epoch 10/20 | training loss: 4.1025 | validation loss: 4.3228
Epoch 11/20 | training loss: 4.0647 | validation loss: 4.3151
Epoch 12/20 | training loss: 4.0290 | validation loss: 4.3030
Epoch 13/20 | training loss: 3.9988 | validation loss: 4.3042
Epoch 14/20 | training loss: 3.9674 | validation loss: 4.2986
Epoch 15/20 | training loss: 3.9403 | validation loss: 4.2874
Epoch 16/20 | training loss: 3.9133 | validation loss: 4.2792
Epoch 17/20 | training loss: 3.8895 | validation loss: 4.2757
Epoch 18/20 | training loss: 3.8673 | validation loss: 4.2754
Epoch 19/20 | training loss: 3.8459 | validation loss: 4.2801
Epoch 20/20 | training loss: 3.8260 | validation loss: 4.2727
Best epoch: 20
Best validation loss: 4.2727
Training time: 17.26 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/english_to_italian_word_rnn.pt

In [ ]:
validation_references, validation_hypotheses = generate_translations(
    english_to_italian_model,
    validation_loader,
    italian_index_to_token,
)

english_to_italian_validation_metrics = compute_translation_metrics(
    validation_references,
    validation_hypotheses,
    target_language="italian",
)

generated_lengths = [
    len(hypothesis)
    for hypothesis in validation_hypotheses
]

empty_percentage = (
    100
    * sum(length == 0 for length in generated_lengths)
    / len(generated_lengths)
)

unique_translations = len(
    set(map(tuple, validation_hypotheses))
)

print("Validation results")
print(
    f"BLEU: "
    f"{english_to_italian_validation_metrics['BLEU']:.2f}"
)
print(
    f"METEOR: "
    f"{english_to_italian_validation_metrics['METEOR']:.2f}"
)
print(f"Empty translations: {empty_percentage:.1f}%")
print(
    f"Mean generated length: "
    f"{np.mean(generated_lengths):.2f} tokens"
)
print(f"Unique translations: {unique_translations:,}")

print("\nMost common generated translations:")
for hypothesis, count in Counter(
    map(tuple, validation_hypotheses)
).most_common(5):
    generated_text = " ".join(hypothesis) or "<empty>"
    print(f"{count:4d} × {generated_text}")

print("\nTranslation examples:")
for i in range(5):
    print(f"\nEN:  {validation_pairs[i][0]}")
    print(f"REF: {' '.join(validation_references[i])}")
    print(
        f"HYP: "
        f"{' '.join(validation_hypotheses[i]) or '<empty>'}"
    )

Validation results
BLEU: 1.89
METEOR: 13.19
Empty translations: 0.0%
Mean generated length: 21.91 tokens
Unique translations: 12,597

Most common generated translations:
  66 × la discussione è chiusa .
  49 × ( applausi )
  46 × signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente , signor presidente
  45 × mi auguro che la commissione non ha mai avuto successo .
  30 × la commissione ha presentato un emendamento orale , che ha svolto un ruolo importante .

Translation examples:

EN:  today i heard you talk of plans approved for spain, which is excellent, but you are saying that malta will be the second phase; when is this second phase going to begin: when it is too late, commissioner?
REF: oggi l’ho sentita parlare di piani approvati per la spagna , ed è magnifico , ma lei sta dicendo che malta rientrerà nella seconda fase : quando inizierà questa seconda fase , quando sarà troppo tardi , signor commissario ?
HYP: signor presidente , signor presidente , signor commissario , onorevoli colleghi , non ho dubbi che la commissione non ha mai avuto la parola , ma non è stato possibile ?

EN:  it may well have been the americans who defeated milosevic by military means, but 90% of the troops keeping the peace there today are europeans.
REF: saranno stati pure gli americani a sconfiggere militarmente milosevic , ma il 90 per cento dei soldati che oggi vi mantengono la pace è europeo .
HYP: la politica di difesa non è stato fatto che la politica di vicinato e la democrazia e la democrazia e la democrazia .

EN:  there can be no doubt this is an exceptional time in terms of material damage and lives lost, especially after the terrible fires in greece, but also in other european regions.
REF: ci troviamo senza ombra di dubbio di fronte a una situazione di proporzioni eccezionali per quanto riguarda i danni materiali e il numero delle vittime , soprattutto a causa dei terribili incendi in grecia , ma anche in altre regioni d'europa .
HYP: e ' vero che la politica di coesione è la nostra solidarietà e la sicurezza dei cittadini , ma anche per la salute pubblica , ma anche per la salute umana .

EN:  mr rovsing's report provides a critical and enriching back-up to the approach of the commission. this report encourages the commission to pursue its efforts and even to go further on some points.
REF: rosving fornisce un sostegno critico ed arricchente alle iniziative della commissione , incoraggiandola a proseguire nei suoi sforzi e persino a fare di più su certi temi .
HYP: la commissione ha svolto un ruolo importante , e la commissione ha svolto un ruolo fondamentale per il parlamento europeo , e non è stato inserito in discussione .

EN:  the poland to lithuania link is mentioned as a project of european interest, and the commission is facilitating progress on that issue.
REF: il collegamento tra polonia e lituania è ritenuto un progetto di interesse europeo , sicché la commissione ne sta promuovendo l’avanzamento .
HYP: la commissione ha proposto un ruolo fondamentale per il programma di lavoro che ha avuto un accordo .

In [11]:
class LSTMEncoder(nn.Module):
    """Encode the English sentence with a single-layer LSTM."""

    def __init__(
        self,
        vocabulary_size,
        embedding_dimension,
        hidden_dimension,
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocabulary_size,
            embedding_dimension,
            padding_idx=PAD_INDEX,
        )

        self.lstm = nn.LSTM(
            embedding_dimension,
            hidden_dimension,
            batch_first=True,
        )

    def forward(self, source, source_lengths):
        embedded = self.embedding(source)

        packed = nn.utils.rnn.pack_padded_sequence(
            embedded,
            source_lengths.cpu(),
            batch_first=True,
            enforce_sorted=False,
        )

        _, state = self.lstm(packed)

        return state


class LSTMDecoder(nn.Module):
    """Decode using the target prefix and fixed encoder context."""

    def __init__(
        self,
        vocabulary_size,
        embedding_dimension,
        hidden_dimension,
    ):
        super().__init__()

        self.embedding = nn.Embedding(
            vocabulary_size,
            embedding_dimension,
            padding_idx=PAD_INDEX,
        )

        self.lstm = nn.LSTM(
            embedding_dimension + hidden_dimension,
            hidden_dimension,
            batch_first=True,
        )

        self.output_layer = nn.Linear(
            hidden_dimension,
            vocabulary_size,
        )

    def forward(self, target_input, state, context):
        embedded = self.embedding(target_input)

        encoder_hidden = context[0][-1]

        repeated_context = encoder_hidden.unsqueeze(1).expand(
            -1,
            target_input.size(1),
            -1,
        )

        decoder_input = torch.cat(
            [embedded, repeated_context],
            dim=-1,
        )

        output, state = self.lstm(decoder_input, state)
        logits = self.output_layer(output)

        return logits, state


class LSTMSeq2Seq(nn.Module):
    """Combine the context-fed LSTM encoder and decoder."""

    def __init__(self, encoder, decoder):
        super().__init__()

        self.encoder = encoder
        self.decoder = decoder

    def forward(self, source, source_lengths, target_input):
        context = self.encoder(source, source_lengths)
        decoder_state = context

        logits, _ = self.decoder(
            target_input,
            decoder_state,
            context,
        )

        return logits


def create_lstm_model(
    source_vocabulary_size,
    target_vocabulary_size,
    embedding_dimension,
    hidden_dimension,
):
    """Create a context-fed LSTM encoder-decoder model."""

    encoder = LSTMEncoder(
        vocabulary_size=source_vocabulary_size,
        embedding_dimension=embedding_dimension,
        hidden_dimension=hidden_dimension,
    )

    decoder = LSTMDecoder(
        vocabulary_size=target_vocabulary_size,
        embedding_dimension=embedding_dimension,
        hidden_dimension=hidden_dimension,
    )

    return LSTMSeq2Seq(encoder, decoder).to(DEVICE)

In [ ]:
LSTM_EMBEDDING_DIMENSION = 64
LSTM_HIDDEN_DIMENSION = 128
LSTM_LEARNING_RATE = 0.001
LSTM_NUMBER_OF_EPOCHS = 20

lstm_model = create_lstm_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=LSTM_HIDDEN_DIMENSION,
)

source_batch, source_lengths, target_batch = next(
    iter(training_loader)
)

source_batch = source_batch.to(DEVICE)
target_batch = target_batch.to(DEVICE)

with torch.no_grad():
    test_logits = lstm_model(
        source_batch,
        source_lengths,
        target_batch[:, :-1],
    )

expected_shape = (
    source_batch.size(0),
    target_batch.size(1) - 1,
    len(italian_token_to_index),
)

assert test_logits.shape == expected_shape

number_of_parameters = sum(
    parameter.numel()
    for parameter in lstm_model.parameters()
)

print(f"Source batch: {source_batch.shape}")
print(f"Target input: {target_batch[:, :-1].shape}")
print(f"Model output: {test_logits.shape}")
print(f"Trainable parameters: {number_of_parameters:,}")

Source batch: torch.Size([128, 47])
Target input: torch.Size([128, 45])
Model output: torch.Size([128, 45, 20000])
Trainable parameters: 5,404,192

In [ ]:
lstm_training_loader = DataLoader(
    training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)

torch.manual_seed(SEED)

lstm_model = create_lstm_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=LSTM_HIDDEN_DIMENSION,
)

lstm_history = run_experiment(
    model=lstm_model,
    training_loader=lstm_training_loader,
    validation_loader=validation_loader,
    checkpoint_name="english_to_italian_context_lstm.pt",
    number_of_epochs=LSTM_NUMBER_OF_EPOCHS,
    learning_rate=LSTM_LEARNING_RATE,
)

Epoch 1/20 | training loss: 6.0564 | validation loss: 5.3353
Epoch 2/20 | training loss: 5.0918 | validation loss: 4.8500
Epoch 3/20 | training loss: 4.7202 | validation loss: 4.6019
Epoch 4/20 | training loss: 4.4953 | validation loss: 4.4450
Epoch 5/20 | training loss: 4.3327 | validation loss: 4.3271
Epoch 6/20 | training loss: 4.2018 | validation loss: 4.2378
Epoch 7/20 | training loss: 4.0921 | validation loss: 4.1641
Epoch 8/20 | training loss: 3.9973 | validation loss: 4.1044
Epoch 9/20 | training loss: 3.9138 | validation loss: 4.0541
Epoch 10/20 | training loss: 3.8384 | validation loss: 4.0083
Epoch 11/20 | training loss: 3.7704 | validation loss: 3.9743
Epoch 12/20 | training loss: 3.7086 | validation loss: 3.9397
Epoch 13/20 | training loss: 3.6523 | validation loss: 3.9156
Epoch 14/20 | training loss: 3.5998 | validation loss: 3.8917
Epoch 15/20 | training loss: 3.5519 | validation loss: 3.8721
Epoch 16/20 | training loss: 3.5072 | validation loss: 3.8552
Epoch 17/20 | training loss: 3.4654 | validation loss: 3.8413
Epoch 18/20 | training loss: 3.4261 | validation loss: 3.8301
Epoch 19/20 | training loss: 3.3895 | validation loss: 3.8195
Epoch 20/20 | training loss: 3.3542 | validation loss: 3.8136
Best epoch: 20
Best validation loss: 3.8136
Training time: 18.31 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/english_to_italian_context_lstm.pt

In [ ]:
lstm_validation_references, lstm_validation_hypotheses = (
    generate_translations(
        lstm_model,
        validation_loader,
        italian_index_to_token,
    )
)

lstm_validation_metrics = compute_translation_metrics(
    lstm_validation_references,
    lstm_validation_hypotheses,
    target_language="italian",
)

generated_lengths = [
    len(hypothesis)
    for hypothesis in lstm_validation_hypotheses
]

empty_percentage = (
    100
    * sum(length == 0 for length in generated_lengths)
    / len(generated_lengths)
)

unique_translations = len(
    set(map(tuple, lstm_validation_hypotheses))
)

print("LSTM validation results")
print(f"BLEU: {lstm_validation_metrics['BLEU']:.2f}")
print(f"METEOR: {lstm_validation_metrics['METEOR']:.2f}")
print(f"Empty translations: {empty_percentage:.1f}%")
print(
    f"Mean generated length: "
    f"{np.mean(generated_lengths):.2f} tokens"
)
print(f"Unique translations: {unique_translations:,}")

print("\nMost common generated translations:")
for hypothesis, count in Counter(
    map(tuple, lstm_validation_hypotheses)
).most_common(5):
    generated_text = " ".join(hypothesis) or "<empty>"
    print(f"{count:4d} × {generated_text}")

print("\nTranslation examples:")
for i in range(5):
    print(f"\nEN:  {validation_pairs[i][0]}")
    print(
        f"REF: "
        f"{' '.join(lstm_validation_references[i])}"
    )
    print(
        f"HYP: "
        f"{' '.join(lstm_validation_hypotheses[i]) or '<empty>'}"
    )

LSTM validation results
BLEU: 4.83
METEOR: 22.26
Empty translations: 0.0%
Mean generated length: 24.86 tokens
Unique translations: 15,424

Most common generated translations:
  46 × la discussione è chiusa .
  46 × ( applausi )
  15 × ( il presidente interrompe l'oratore )
  11 × .
  10 × grazie , signor commissario .

Translation examples:

EN:  today i heard you talk of plans approved for spain, which is excellent, but you are saying that malta will be the second phase; when is this second phase going to begin: when it is too late, commissioner?
REF: oggi l’ho sentita parlare di piani approvati per la spagna , ed è magnifico , ma lei sta dicendo che malta rientrerà nella seconda fase : quando inizierà questa seconda fase , quando sarà troppo tardi , signor commissario ?
HYP: oggi non vi è la parola che la signora commissario , se si è trattato di lisbona , ma è ora che , in primo luogo , ma oggi , in cui si è detto : il primo ministro , che è ora in corso ?

EN:  it may well have been the americans who defeated milosevic by military means, but 90% of the troops keeping the peace there today are europeans.
REF: saranno stati pure gli americani a sconfiggere militarmente milosevic , ma il 90 per cento dei soldati che oggi vi mantengono la pace è europeo .
HYP: e ' evidente che i capi di stato di governo di cui si sono impegnati a causa di un paese che si è abbattuta che il popolo iracheno è stato un paese che si sta facendo il potere di pace .

EN:  there can be no doubt this is an exceptional time in terms of material damage and lives lost, especially after the terrible fires in greece, but also in other european regions.
REF: ci troviamo senza ombra di dubbio di fronte a una situazione di proporzioni eccezionali per quanto riguarda i danni materiali e il numero delle vittime , soprattutto a causa dei terribili incendi in grecia , ma anche in altre regioni d'europa .
HYP: non è solo solo un dibattito più importante , ma anche in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , in particolare , anche in particolare in europa .

EN:  mr rovsing's report provides a critical and enriching back-up to the approach of the commission. this report encourages the commission to pursue its efforts and even to go further on some points.
REF: rosving fornisce un sostegno critico ed arricchente alle iniziative della commissione , incoraggiandola a proseguire nei suoi sforzi e persino a fare di più su certi temi .
HYP: la relazione dell'onorevole garosci ha giustamente sottolineato , e la commissione ha presentato una relazione e la commissione per la sua relazione , che si è impegnata a presentare una serie di proposte .

EN:  the poland to lithuania link is mentioned as a project of european interest, and the commission is facilitating progress on that issue.
REF: il collegamento tra polonia e lituania è ritenuto un progetto di interesse europeo , sicché la commissione ne sta promuovendo l’avanzamento .
HYP: la commissione europea ha un ruolo che il parlamento europeo ha un ruolo importante che il parlamento europeo ha svolto un ruolo importante .

### LSTM hyperparameter tuning

In [ ]:
LSTM_TUNING_EPOCHS = 15

lstm_tuning_configurations = [
    {
        "name": "e64_h256",
        "embedding_dimension": 64,
        "hidden_dimension": 256,
        "learning_rate": 0.001,
    },
    {
        "name": "e128_h256",
        "embedding_dimension": 128,
        "hidden_dimension": 256,
        "learning_rate": 0.001,
    },
    {
        "name": "e128_h512",
        "embedding_dimension": 128,
        "hidden_dimension": 512,
        "learning_rate": 0.001,
    },
    {
        "name": "e128_h512_lower_lr",
        "embedding_dimension": 128,
        "hidden_dimension": 512,
        "learning_rate": 0.0005,
    },
]

lstm_tuning_results = []

for configuration in lstm_tuning_configurations:
    print(f"\nConfiguration: {configuration['name']}")

    torch.manual_seed(SEED)

    lstm_tuning_training_loader = DataLoader(
        tuning_training_dataset,
        batch_size=BATCH_SIZE,
        shuffle=True,
        collate_fn=collate_batch,
        generator=torch.Generator().manual_seed(SEED),
    )

    tuning_lstm_model = create_lstm_model(
        source_vocabulary_size=len(english_token_to_index),
        target_vocabulary_size=len(italian_token_to_index),
        embedding_dimension=configuration["embedding_dimension"],
        hidden_dimension=configuration["hidden_dimension"],
    )

    history = run_experiment(
        model=tuning_lstm_model,
        training_loader=lstm_tuning_training_loader,
        validation_loader=tuning_validation_loader,
        checkpoint_name=(
            f"lstm_tuning_{configuration['name']}.pt"
        ),
        number_of_epochs=LSTM_TUNING_EPOCHS,
        learning_rate=configuration["learning_rate"],
    )

    references, hypotheses = generate_translations(
        tuning_lstm_model,
        tuning_validation_loader,
        italian_index_to_token,
    )

    metrics = compute_translation_metrics(
        references,
        hypotheses,
        target_language="italian",
    )

    best_epoch_index = int(
        np.argmin(history["validation_loss"])
    )

    number_of_parameters = sum(
        parameter.numel()
        for parameter in tuning_lstm_model.parameters()
    )

    lstm_tuning_results.append(
        {
            **configuration,
            "best_epoch": best_epoch_index + 1,
            "training_loss": history[
                "training_loss"
            ][best_epoch_index],
            "validation_loss": history[
                "validation_loss"
            ][best_epoch_index],
            "BLEU": metrics["BLEU"],
            "METEOR": metrics["METEOR"],
            "parameters": number_of_parameters,
            "training_minutes": (
                history["elapsed_seconds"] / 60
            ),
        }
    )

    print(f"Validation BLEU: {metrics['BLEU']:.2f}")
    print(f"Validation METEOR: {metrics['METEOR']:.2f}")

Configuration: e64_h256
Epoch 1/15 | training loss: 5.8682 | validation loss: 5.0821
Epoch 2/15 | training loss: 4.8199 | validation loss: 4.5846
Epoch 3/15 | training loss: 4.4240 | validation loss: 4.3281
Epoch 4/15 | training loss: 4.1644 | validation loss: 4.1546
Epoch 5/15 | training loss: 3.9654 | validation loss: 4.0246
Epoch 6/15 | training loss: 3.8021 | validation loss: 3.9325
Epoch 7/15 | training loss: 3.6637 | validation loss: 3.8571
Epoch 8/15 | training loss: 3.5426 | validation loss: 3.7982
Epoch 9/15 | training loss: 3.4359 | validation loss: 3.7543
Epoch 10/15 | training loss: 3.3400 | validation loss: 3.7216
Epoch 11/15 | training loss: 3.2539 | validation loss: 3.6978
Epoch 12/15 | training loss: 3.1757 | validation loss: 3.6772
Epoch 13/15 | training loss: 3.1039 | validation loss: 3.6693
Epoch 14/15 | training loss: 3.0372 | validation loss: 3.6624
Epoch 15/15 | training loss: 2.9759 | validation loss: 3.6612
Best epoch: 15
Best validation loss: 3.6612
Training time: 20.04 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/lstm_tuning_e64_h256.pt
Validation BLEU: 5.96
Validation METEOR: 24.93

Configuration: e128_h256
Epoch 1/15 | training loss: 5.6753 | validation loss: 4.8823
Epoch 2/15 | training loss: 4.6342 | validation loss: 4.4171
Epoch 3/15 | training loss: 4.2455 | validation loss: 4.1707
Epoch 4/15 | training loss: 3.9845 | validation loss: 4.0063
Epoch 5/15 | training loss: 3.7832 | validation loss: 3.8860
Epoch 6/15 | training loss: 3.6184 | validation loss: 3.8060
Epoch 7/15 | training loss: 3.4792 | validation loss: 3.7399
Epoch 8/15 | training loss: 3.3590 | validation loss: 3.6969
Epoch 9/15 | training loss: 3.2517 | validation loss: 3.6657
Epoch 10/15 | training loss: 3.1559 | validation loss: 3.6436
Epoch 11/15 | training loss: 3.0684 | validation loss: 3.6394
Epoch 12/15 | training loss: 2.9881 | validation loss: 3.6268
Epoch 13/15 | training loss: 2.9133 | validation loss: 3.6303
Epoch 14/15 | training loss: 2.8436 | validation loss: 3.6308
Epoch 15/15 | training loss: 2.7780 | validation loss: 3.6442
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 12
Best validation loss: 3.6268
Training time: 20.48 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/lstm_tuning_e128_h256.pt
Validation BLEU: 5.87
Validation METEOR: 24.72

Configuration: e128_h512
Epoch 1/15 | training loss: 5.5526 | validation loss: 4.7277
Epoch 2/15 | training loss: 4.4378 | validation loss: 4.2142
Epoch 3/15 | training loss: 3.9733 | validation loss: 3.9343
Epoch 4/15 | training loss: 3.6476 | validation loss: 3.7588
Epoch 5/15 | training loss: 3.3940 | validation loss: 3.6489
Epoch 6/15 | training loss: 3.1826 | validation loss: 3.5837
Epoch 7/15 | training loss: 3.0009 | validation loss: 3.5451
Epoch 8/15 | training loss: 2.8393 | validation loss: 3.5323
Epoch 9/15 | training loss: 2.6930 | validation loss: 3.5314
Epoch 10/15 | training loss: 2.5589 | validation loss: 3.5495
Epoch 11/15 | training loss: 2.4362 | validation loss: 3.5727
Epoch 12/15 | training loss: 2.3227 | validation loss: 3.6060
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 9
Best validation loss: 3.5314
Training time: 29.65 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/lstm_tuning_e128_h512.pt
Validation BLEU: 6.80
Validation METEOR: 26.68

Configuration: e128_h512_lower_lr
Epoch 1/15 | training loss: 5.8383 | validation loss: 5.0671
Epoch 2/15 | training loss: 4.7964 | validation loss: 4.5531
Epoch 3/15 | training loss: 4.3761 | validation loss: 4.2693
Epoch 4/15 | training loss: 4.0841 | validation loss: 4.0650
Epoch 5/15 | training loss: 3.8533 | validation loss: 3.9149
Epoch 6/15 | training loss: 3.6595 | validation loss: 3.8081
Epoch 7/15 | training loss: 3.4926 | validation loss: 3.7212
Epoch 8/15 | training loss: 3.3453 | validation loss: 3.6561
Epoch 9/15 | training loss: 3.2129 | validation loss: 3.6086
Epoch 10/15 | training loss: 3.0920 | validation loss: 3.5745
Epoch 11/15 | training loss: 2.9804 | validation loss: 3.5510
Epoch 12/15 | training loss: 2.8761 | validation loss: 3.5385
Epoch 13/15 | training loss: 2.7780 | validation loss: 3.5370
Epoch 14/15 | training loss: 2.6849 | validation loss: 3.5322
Epoch 15/15 | training loss: 2.5972 | validation loss: 3.5414
Best epoch: 14
Best validation loss: 3.5322
Training time: 37.01 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/lstm_tuning_e128_h512_lower_lr.pt
Validation BLEU: 7.24
Validation METEOR: 27.41

In [ ]:
lstm_tuning_results_table = pd.DataFrame(
    lstm_tuning_results
)

lstm_tuning_results_table = lstm_tuning_results_table[
    [
        "name",
        "embedding_dimension",
        "hidden_dimension",
        "learning_rate",
        "best_epoch",
        "training_loss",
        "validation_loss",
        "BLEU",
        "METEOR",
        "parameters",
        "training_minutes",
    ]
].sort_values("validation_loss")

display(
    lstm_tuning_results_table.round(
        {
            "training_loss": 4,
            "validation_loss": 4,
            "BLEU": 2,
            "METEOR": 2,
            "training_minutes": 2,
        }
    )
)

best_lstm_configuration = min(
    lstm_tuning_results,
    key=lambda result: result["validation_loss"],
)

BEST_LSTM_EMBEDDING_DIMENSION = (
    best_lstm_configuration["embedding_dimension"]
)
BEST_LSTM_HIDDEN_DIMENSION = (
    best_lstm_configuration["hidden_dimension"]
)
BEST_LSTM_LEARNING_RATE = (
    best_lstm_configuration["learning_rate"]
)

lstm_tuning_results_path = (
    RESULTS_DIR
    / "lstm_hyperparameter_tuning_results.csv"
)

lstm_tuning_results_table.to_csv(
    lstm_tuning_results_path,
    index=False,
)

print(
    f"Selected configuration: "
    f"{best_lstm_configuration['name']}"
)
print(
    f"Embedding dimension: "
    f"{BEST_LSTM_EMBEDDING_DIMENSION}"
)
print(
    f"Hidden dimension: "
    f"{BEST_LSTM_HIDDEN_DIMENSION}"
)
print(
    f"Learning rate: "
    f"{BEST_LSTM_LEARNING_RATE}"
)
print(f"Saved results: {lstm_tuning_results_path}")

,name,embedding_dimension,hidden_dimension,learning_rate,best_epoch,training_loss,validation_loss,BLEU,METEOR,parameters,training_minutes
2,e128_h512,128,512,0.0010,9,2.6930,3.5314,6.80,26.68,19058208,29.65
3,e128_h512_lower_lr,128,512,0.0005,14,2.6849,3.5322,7.24,27.41,19058208,37.01
1,e128_h256,128,256,0.0010,12,2.9881,3.6268,5.87,24.72,11312672,20.48
0,e64_h256,64,256,0.0010,15,2.9759,3.6612,5.96,24.93,8621600,20.04

Selected configuration: e128_h512
Embedding dimension: 128
Hidden dimension: 512
Learning rate: 0.001
Saved results: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/lstm_hyperparameter_tuning_results.csv

### Final LSTM model

In [ ]:
LARGE_LSTM_NUMBER_OF_EPOCHS = 30

large_lstm_training_loader = DataLoader(
    training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)

torch.manual_seed(SEED)

large_lstm_model = create_lstm_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=BEST_LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_LSTM_HIDDEN_DIMENSION,
)

large_lstm_history = run_experiment(
    model=large_lstm_model,
    training_loader=large_lstm_training_loader,
    validation_loader=validation_loader,
    checkpoint_name="english_to_italian_context_lstm_large.pt",
    number_of_epochs=LARGE_LSTM_NUMBER_OF_EPOCHS,
    learning_rate=BEST_LSTM_LEARNING_RATE,
)

Epoch 1/30 | training loss: 5.5526 | validation loss: 4.7277
Epoch 2/30 | training loss: 4.4378 | validation loss: 4.2142
Epoch 3/30 | training loss: 3.9733 | validation loss: 3.9343
Epoch 4/30 | training loss: 3.6476 | validation loss: 3.7588
Epoch 5/30 | training loss: 3.3940 | validation loss: 3.6489
Epoch 6/30 | training loss: 3.1826 | validation loss: 3.5837
Epoch 7/30 | training loss: 3.0009 | validation loss: 3.5451
Epoch 8/30 | training loss: 2.8393 | validation loss: 3.5323
Epoch 9/30 | training loss: 2.6930 | validation loss: 3.5314
Epoch 10/30 | training loss: 2.5589 | validation loss: 3.5495
Epoch 11/30 | training loss: 2.4362 | validation loss: 3.5727
Epoch 12/30 | training loss: 2.3227 | validation loss: 3.6060
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 9
Best validation loss: 3.5314
Training time: 29.58 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/english_to_italian_context_lstm_large.pt

In [ ]:
large_lstm_validation_references, large_lstm_validation_hypotheses = (
    generate_translations(
        large_lstm_model,
        validation_loader,
        italian_index_to_token,
    )
)

large_lstm_validation_metrics = compute_translation_metrics(
    large_lstm_validation_references,
    large_lstm_validation_hypotheses,
    target_language="italian",
)

generated_lengths = [
    len(hypothesis)
    for hypothesis in large_lstm_validation_hypotheses
]

empty_percentage = (
    100
    * sum(length == 0 for length in generated_lengths)
    / len(generated_lengths)
)

unique_translations = len(
    set(map(tuple, large_lstm_validation_hypotheses))
)

print("Large LSTM validation results")
print(
    f"BLEU: "
    f"{large_lstm_validation_metrics['BLEU']:.2f}"
)
print(
    f"METEOR: "
    f"{large_lstm_validation_metrics['METEOR']:.2f}"
)
print(f"Empty translations: {empty_percentage:.1f}%")
print(
    f"Mean generated length: "
    f"{np.mean(generated_lengths):.2f} tokens"
)
print(f"Unique translations: {unique_translations:,}")

print("\nMost common generated translations:")
for hypothesis, count in Counter(
    map(tuple, large_lstm_validation_hypotheses)
).most_common(5):
    generated_text = " ".join(hypothesis) or "<empty>"
    print(f"{count:4d} × {generated_text}")

print("\nTranslation examples:")
for i in range(5):
    print(f"\nEN:  {validation_pairs[i][0]}")
    print(
        f"REF: "
        f"{' '.join(large_lstm_validation_references[i])}"
    )
    print(
        f"HYP: "
        f"{' '.join(large_lstm_validation_hypotheses[i]) or '<empty>'}"
    )

Large LSTM validation results
BLEU: 6.80
METEOR: 26.68
Empty translations: 0.0%
Mean generated length: 23.85 tokens
Unique translations: 15,472

Most common generated translations:
  46 × la discussione è chiusa .
  46 × ( applausi )
  15 × ( il presidente interrompe l'oratore )
  10 × la ringrazio , signor commissario .
   9 × grazie .

Translation examples:

EN:  today i heard you talk of plans approved for spain, which is excellent, but you are saying that malta will be the second phase; when is this second phase going to begin: when it is too late, commissioner?
REF: oggi l’ho sentita parlare di piani approvati per la spagna , ed è magnifico , ma lei sta dicendo che malta rientrerà nella seconda fase : quando inizierà questa seconda fase , quando sarà troppo tardi , signor commissario ?
HYP: ho parlato di una frase economica della presidenza ungherese , ma in questo senso , secondo la quale la relazione è in realtà , ma è evidente che la sua posizione è in cui si è verificato , ma è proprio questo punto che è la sua decisione ?

EN:  it may well have been the americans who defeated milosevic by military means, but 90% of the troops keeping the peace there today are europeans.
REF: saranno stati pure gli americani a sconfiggere militarmente milosevic , ma il 90 per cento dei soldati che oggi vi mantengono la pace è europeo .
HYP: sarebbe assurdo , ma le truppe armate , i militari palestinesi , mentre i palestinesi hanno ancora la morte di gaza , ma la popolazione è stata vittima di una popolazione di gaza .

EN:  there can be no doubt this is an exceptional time in terms of material damage and lives lost, especially after the terrible fires in greece, but also in other european regions.
REF: ci troviamo senza ombra di dubbio di fronte a una situazione di proporzioni eccezionali per quanto riguarda i danni materiali e il numero delle vittime , soprattutto a causa dei terribili incendi in grecia , ma anche in altre regioni d'europa .
HYP: non vi è ancora una differenza di un errore che si sono ancora in carcere e in altre centrali , ma anche in altre regioni dell'inghilterra , come avviene in molti secoli , anche in altre regioni europee .

EN:  mr rovsing's report provides a critical and enriching back-up to the approach of the commission. this report encourages the commission to pursue its efforts and even to go further on some points.
REF: rosving fornisce un sostegno critico ed arricchente alle iniziative della commissione , incoraggiandola a proseguire nei suoi sforzi e persino a fare di più su certi temi .
HYP: la relazione dell’onorevole díez gonzález è molto utile e una relazione sulla commissione , e deve quindi invitare la commissione a presentare una risposta adeguata alla sua relazione e di presentare una risposta più chiara .

EN:  the poland to lithuania link is mentioned as a project of european interest, and the commission is facilitating progress on that issue.
REF: il collegamento tra polonia e lituania è ritenuto un progetto di interesse europeo , sicché la commissione ne sta promuovendo l’avanzamento .
HYP: la commissione europea ha svolto un particolare rilievo alla ricerca di questa direttiva e la commissione dovrebbe fare in modo tale aspetto .

In [ ]:
lstm_model_comparison = pd.DataFrame(
    [
        {
            "model": "medium_lstm",
            "embedding_dimension": 64,
            "hidden_dimension": 128,
            "validation_loss": lstm_history[
                "best_validation_loss"
            ],
            "BLEU": lstm_validation_metrics["BLEU"],
            "METEOR": lstm_validation_metrics["METEOR"],
            "training_minutes": (
                lstm_history["elapsed_seconds"] / 60
            ),
        },
        {
            "model": "large_lstm",
            "embedding_dimension": (
                BEST_LSTM_EMBEDDING_DIMENSION
            ),
            "hidden_dimension": (
                BEST_LSTM_HIDDEN_DIMENSION
            ),
            "validation_loss": large_lstm_history[
                "best_validation_loss"
            ],
            "BLEU": large_lstm_validation_metrics["BLEU"],
            "METEOR": large_lstm_validation_metrics["METEOR"],
            "training_minutes": (
                large_lstm_history["elapsed_seconds"] / 60
            ),
        },
    ]
)

display(lstm_model_comparison.round(2))

comparison_path = (
    RESULTS_DIR / "lstm_model_comparison.csv"
)

lstm_model_comparison.to_csv(
    comparison_path,
    index=False,
)

print(f"Saved comparison: {comparison_path}")

,model,embedding_dimension,hidden_dimension,validation_loss,BLEU,METEOR,training_minutes
0,medium_lstm,64,128,3.81,4.83,22.26,18.31
1,large_lstm,128,512,3.53,6.80,26.68,29.58

Saved comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/lstm_model_comparison.csv

## 7. Embedding comparison

In [ ]:
from gensim.models import Word2Vec

WORD2VEC_DIMENSION = BEST_LSTM_EMBEDDING_DIMENSION
WORD2VEC_WINDOW = 5
WORD2VEC_MIN_COUNT = 2
WORD2VEC_EPOCHS = 20


english_word2vec_sentences = [
    tokenize(english)
    for english, _ in training_pairs
]

italian_word2vec_sentences = [
    tokenize(italian)
    for _, italian in training_pairs
]


word2vec_start_time = time.perf_counter()

english_word2vec_model = Word2Vec(
    sentences=english_word2vec_sentences,
    vector_size=WORD2VEC_DIMENSION,
    window=WORD2VEC_WINDOW,
    min_count=WORD2VEC_MIN_COUNT,
    workers=1,
    sg=0,
    epochs=WORD2VEC_EPOCHS,
    seed=SEED,
)

italian_word2vec_model = Word2Vec(
    sentences=italian_word2vec_sentences,
    vector_size=WORD2VEC_DIMENSION,
    window=WORD2VEC_WINDOW,
    min_count=WORD2VEC_MIN_COUNT,
    workers=1,
    sg=0,
    epochs=WORD2VEC_EPOCHS,
    seed=SEED,
)

word2vec_preparation_seconds = (
    time.perf_counter() - word2vec_start_time
)


english_word2vec_path = (
    MODEL_DIR / "english_word2vec.model"
)
italian_word2vec_path = (
    MODEL_DIR / "italian_word2vec.model"
)

english_word2vec_model.save(
    str(english_word2vec_path)
)
italian_word2vec_model.save(
    str(italian_word2vec_path)
)


def initialise_embedding_from_word2vec(
    embedding_layer,
    token_to_index,
    word2vec_model,
):
    """Copy available Word2Vec vectors into an embedding layer."""

    vocabulary_tokens = [
        token
        for token in token_to_index
        if token not in SPECIAL_TOKENS
    ]

    matched_tokens = 0

    with torch.no_grad():
        for token in vocabulary_tokens:
            if token not in word2vec_model.wv:
                continue

            token_index = token_to_index[token]

            vector = torch.tensor(
                word2vec_model.wv[token],
                dtype=embedding_layer.weight.dtype,
                device=embedding_layer.weight.device,
            )

            embedding_layer.weight[token_index].copy_(vector)
            matched_tokens += 1

    coverage = matched_tokens / len(vocabulary_tokens)

    return matched_tokens, coverage


print(
    f"English Word2Vec vocabulary: "
    f"{len(english_word2vec_model.wv):,}"
)
print(
    f"Italian Word2Vec vocabulary: "
    f"{len(italian_word2vec_model.wv):,}"
)
print(
    f"Preparation time: "
    f"{word2vec_preparation_seconds / 60:.2f} minutes"
)
print(f"Saved English model: {english_word2vec_path}")
print(f"Saved Italian model: {italian_word2vec_path}")

NameError: name 'BEST_LSTM_EMBEDDING_DIMENSION' is not defined

In [ ]:
WORD2VEC_LSTM_NUMBER_OF_EPOCHS = 30


# Recreate the same deterministic training order.
word2vec_training_loader = DataLoader(
    training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)


# Create the same large LSTM architecture.
torch.manual_seed(SEED)

word2vec_lstm_model = create_lstm_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=BEST_LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_LSTM_HIDDEN_DIMENSION,
)

english_matched_tokens, english_embedding_coverage = (
    initialise_embedding_from_word2vec(
        word2vec_lstm_model.encoder.embedding,
        english_token_to_index,
        english_word2vec_model,
    )
)

italian_matched_tokens, italian_embedding_coverage = (
    initialise_embedding_from_word2vec(
        word2vec_lstm_model.decoder.embedding,
        italian_token_to_index,
        italian_word2vec_model,
    )
)

assert word2vec_lstm_model.encoder.embedding.weight.requires_grad
assert word2vec_lstm_model.decoder.embedding.weight.requires_grad

print(
    f"English embedding coverage: "
    f"{english_matched_tokens:,} tokens "
    f"({english_embedding_coverage:.1%})"
)
print(
    f"Italian embedding coverage: "
    f"{italian_matched_tokens:,} tokens "
    f"({italian_embedding_coverage:.1%})"
)

word2vec_lstm_history = run_experiment(
    model=word2vec_lstm_model,
    training_loader=word2vec_training_loader,
    validation_loader=validation_loader,
    checkpoint_name=(
        "english_to_italian_context_lstm_large_word2vec.pt"
    ),
    number_of_epochs=WORD2VEC_LSTM_NUMBER_OF_EPOCHS,
    learning_rate=BEST_LSTM_LEARNING_RATE,
)

word2vec_validation_references, word2vec_validation_hypotheses = (
    generate_translations(
        word2vec_lstm_model,
        validation_loader,
        italian_index_to_token,
    )
)

word2vec_validation_metrics = compute_translation_metrics(
    word2vec_validation_references,
    word2vec_validation_hypotheses,
    target_language="italian",
)


random_mean_length = np.mean(
    [
        len(hypothesis)
        for hypothesis in large_lstm_validation_hypotheses
    ]
)

word2vec_mean_length = np.mean(
    [
        len(hypothesis)
        for hypothesis in word2vec_validation_hypotheses
    ]
)

random_unique_translations = len(
    set(map(tuple, large_lstm_validation_hypotheses))
)

word2vec_unique_translations = len(
    set(map(tuple, word2vec_validation_hypotheses))
)


embedding_comparison = pd.DataFrame(
    [
        {
            "embedding": "learned_from_scratch",
            "validation_loss": large_lstm_history[
                "best_validation_loss"
            ],
            "BLEU": large_lstm_validation_metrics["BLEU"],
            "METEOR": large_lstm_validation_metrics["METEOR"],
            "mean_generated_length": random_mean_length,
            "unique_translations": random_unique_translations,
            "embedding_preparation_minutes": 0.0,
            "training_minutes": (
                large_lstm_history["elapsed_seconds"] / 60
            ),
        },
        {
            "embedding": "word2vec_initialisation",
            "validation_loss": word2vec_lstm_history[
                "best_validation_loss"
            ],
            "BLEU": word2vec_validation_metrics["BLEU"],
            "METEOR": word2vec_validation_metrics["METEOR"],
            "mean_generated_length": word2vec_mean_length,
            "unique_translations": word2vec_unique_translations,
            "embedding_preparation_minutes": (
                word2vec_preparation_seconds / 60
            ),
            "training_minutes": (
                word2vec_lstm_history["elapsed_seconds"] / 60
            ),
        },
    ]
)

display(
    embedding_comparison.round(
        {
            "validation_loss": 4,
            "BLEU": 2,
            "METEOR": 2,
            "mean_generated_length": 2,
            "embedding_preparation_minutes": 2,
            "training_minutes": 2,
        }
    )
)


embedding_comparison_path = (
    RESULTS_DIR / "embedding_comparison.csv"
)

embedding_comparison.to_csv(
    embedding_comparison_path,
    index=False,
)

print("\nWord2Vec validation results")
print(f"BLEU: {word2vec_validation_metrics['BLEU']:.2f}")
print(f"METEOR: {word2vec_validation_metrics['METEOR']:.2f}")
print(f"Saved comparison: {embedding_comparison_path}")


print("\nWord2Vec translation examples:")
for i in range(5):
    print(f"\nEN:  {validation_pairs[i][0]}")
    print(
        f"REF: "
        f"{' '.join(word2vec_validation_references[i])}"
    )
    print(
        f"HYP: "
        f"{' '.join(word2vec_validation_hypotheses[i]) or '<empty>'}"
    )

English embedding coverage: 19,585 tokens (97.9%)
Italian embedding coverage: 19,996 tokens (100.0%)
Epoch 1/30 | training loss: 5.0325 | validation loss: 4.2211
Epoch 2/30 | training loss: 3.9101 | validation loss: 3.7347
Epoch 3/30 | training loss: 3.4623 | validation loss: 3.4982
Epoch 4/30 | training loss: 3.1624 | validation loss: 3.3648
Epoch 5/30 | training loss: 2.9303 | validation loss: 3.2940
Epoch 6/30 | training loss: 2.7345 | validation loss: 3.2616
Epoch 7/30 | training loss: 2.5639 | validation loss: 3.2506
Epoch 8/30 | training loss: 2.4110 | validation loss: 3.2552
Epoch 9/30 | training loss: 2.2727 | validation loss: 3.2792
Epoch 10/30 | training loss: 2.1457 | validation loss: 3.3134
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 7
Best validation loss: 3.2506
Training time: 24.67 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/english_to_italian_context_lstm_large_word2vec.pt

,embedding,validation_loss,BLEU,METEOR,mean_generated_length,unique_translations,embedding_preparation_minutes,training_minutes
0,learned_from_scratch,3.5314,6.8,26.68,23.85,15472,0.00,29.58
1,word2vec_initialisation,3.2506,7.2,28.25,23.95,15460,2.86,24.67

Word2Vec validation results
BLEU: 7.20
METEOR: 28.25
Saved comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/embedding_comparison.csv

Word2Vec translation examples:

EN:  today i heard you talk of plans approved for spain, which is excellent, but you are saying that malta will be the second phase; when is this second phase going to begin: when it is too late, commissioner?
REF: oggi l’ho sentita parlare di piani approvati per la spagna , ed è magnifico , ma lei sta dicendo che malta rientrerà nella seconda fase : quando inizierà questa seconda fase , quando sarà troppo tardi , signor commissario ?
HYP: oggi ci sono pervenuti a quanto ho sentito , ma le osservazioni di fondo sono state iscritte in primo luogo , quando la grecia è la prossima estate , ma la cosa sarà la signora commissario schreyer ?

EN:  it may well have been the americans who defeated milosevic by military means, but 90% of the troops keeping the peace there today are europeans.
REF: saranno stati pure gli americani a sconfiggere militarmente milosevic , ma il 90 per cento dei soldati che oggi vi mantengono la pace è europeo .
HYP: sono inoltre gli unici che saddam hussein a pechino , ma , a volte , i terroristi sono responsabili della guerra , mentre il popolo cinese ha già detto .

EN:  there can be no doubt this is an exceptional time in terms of material damage and lives lost, especially after the terrible fires in greece, but also in other european regions.
REF: ci troviamo senza ombra di dubbio di fronte a una situazione di proporzioni eccezionali per quanto riguarda i danni materiali e il numero delle vittime , soprattutto a causa dei terribili incendi in grecia , ma anche in altre regioni d'europa .
HYP: non vi è alcun dubbio in questo contesto , ma anche per le malattie infettive , e soprattutto in questo caso , le inondazioni sono già in aumento delle aree urbane in portogallo .

EN:  mr rovsing's report provides a critical and enriching back-up to the approach of the commission. this report encourages the commission to pursue its efforts and even to go further on some points.
REF: rosving fornisce un sostegno critico ed arricchente alle iniziative della commissione , incoraggiandola a proseguire nei suoi sforzi e persino a fare di più su certi temi .
HYP: la relazione dell'onorevole colajanni è una relazione e più decisa e la commissione intende adottare una posizione più incisiva e più decisa in tal senso .

EN:  the poland to lithuania link is mentioned as a project of european interest, and the commission is facilitating progress on that issue.
REF: il collegamento tra polonia e lituania è ritenuto un progetto di interesse europeo , sicché la commissione ne sta promuovendo l’avanzamento .
HYP: la polonia in polonia è la commissione europea per la cultura e la cooperazione con i paesi terzi .

## Final English-to-Italian test evaluation

In [ ]:
FINAL_EN_IT_CHECKPOINT = (
    MODEL_DIR
    / "english_to_italian_context_lstm_large_word2vec.pt"
)


# Recreate the selected architecture and load its best checkpoint.
final_en_it_model = create_lstm_model(
    source_vocabulary_size=len(english_token_to_index),
    target_vocabulary_size=len(italian_token_to_index),
    embedding_dimension=BEST_LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_LSTM_HIDDEN_DIMENSION,
)

final_en_it_model.load_state_dict(
    torch.load(
        FINAL_EN_IT_CHECKPOINT,
        map_location=DEVICE,
    )
)


# Generate the test translations once.
inference_start_time = time.perf_counter()

en_it_test_references, en_it_test_hypotheses = (
    generate_translations(
        final_en_it_model,
        test_loader,
        italian_index_to_token,
    )
)

en_it_test_inference_seconds = (
    time.perf_counter() - inference_start_time
)


# Compute the final test metrics.
en_it_test_metrics = compute_translation_metrics(
    en_it_test_references,
    en_it_test_hypotheses,
    target_language="italian",
)

test_generated_lengths = [
    len(hypothesis)
    for hypothesis in en_it_test_hypotheses
]

test_empty_percentage = (
    100
    * sum(
        length == 0
        for length in test_generated_lengths
    )
    / len(test_generated_lengths)
)

test_unique_translations = len(
    set(map(tuple, en_it_test_hypotheses))
)

en_it_test_translations_table = pd.DataFrame(
    {
        "source_english": [
            english
            for english, _ in test_pairs
        ],
        "reference_italian": [
            " ".join(reference)
            for reference in en_it_test_references
        ],
        "hypothesis_italian": [
            " ".join(hypothesis)
            for hypothesis in en_it_test_hypotheses
        ],
        "source_length": [
            len(tokenize(english))
            for english, _ in test_pairs
        ],
        "reference_length": [
            len(reference)
            for reference in en_it_test_references
        ],
        "hypothesis_length": test_generated_lengths,
    }
)

en_it_test_translations_path = (
    RESULTS_DIR
    / "english_to_italian_test_translations.csv"
)

en_it_test_translations_table.to_csv(
    en_it_test_translations_path,
    index=False,
)

en_it_test_results = pd.DataFrame(
    [
        {
            "direction": "English_to_Italian",
            "model": "context_lstm_large_word2vec",
            "test_examples": len(test_pairs),
            "BLEU": en_it_test_metrics["BLEU"],
            "METEOR": en_it_test_metrics["METEOR"],
            "mean_generated_length": np.mean(
                test_generated_lengths
            ),
            "empty_translations_percentage": (
                test_empty_percentage
            ),
            "unique_translations": (
                test_unique_translations
            ),
            "inference_minutes": (
                en_it_test_inference_seconds / 60
            ),
        }
    ]
)

en_it_test_results_path = (
    RESULTS_DIR
    / "english_to_italian_test_results.csv"
)

en_it_test_results.to_csv(
    en_it_test_results_path,
    index=False,
)


print("Final English-to-Italian test results")
print(f"BLEU: {en_it_test_metrics['BLEU']:.2f}")
print(f"METEOR: {en_it_test_metrics['METEOR']:.2f}")
print(
    f"Empty translations: "
    f"{test_empty_percentage:.1f}%"
)
print(
    f"Mean generated length: "
    f"{np.mean(test_generated_lengths):.2f} tokens"
)
print(
    f"Unique translations: "
    f"{test_unique_translations:,}"
)
print(
    f"Inference time: "
    f"{en_it_test_inference_seconds / 60:.2f} minutes"
)

print(
    f"\nSaved results: "
    f"{en_it_test_results_path}"
)
print(
    f"Saved translations: "
    f"{en_it_test_translations_path}"
)


print("\nTest translation examples:")
for i in range(5):
    print(f"\nEN:  {test_pairs[i][0]}")
    print(
        f"REF: "
        f"{' '.join(en_it_test_references[i])}"
    )
    print(
        f"HYP: "
        f"{' '.join(en_it_test_hypotheses[i]) or '<empty>'}"
    )

Final English-to-Italian test results
BLEU: 7.26
METEOR: 28.12
Empty translations: 0.0%
Mean generated length: 23.93 tokens
Unique translations: 30,792
Inference time: 0.41 minutes

Saved results: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/english_to_italian_test_results.csv
Saved translations: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/english_to_italian_test_translations.csv

Test translation examples:

EN:  request for the defence of parliamentary immunity: see minutes
REF: richiesta di difesa dell'immunità parlamentare : vedasi processo verbale
HYP: richiesta di revoca dell'immunità parlamentare : vedasi processo verbale

EN:  when will that be?
REF: quando ?
HYP: quando sarà ?

EN:  evidently, articles 23 and 24 of the funds coordinating regulation.
REF: naturalmente gli articoli 23 e 24 del regolamento per il coordinamento dei fondi .
HYP: in base all'articolo 4 , i paragrafi e i regolamenti relativi al regolamento .

EN:  the possibility of developing a strategy and research agenda on this subject will be examined, so that the relevant problems can be identified and proposals can be made for possible ways of addressing them.
REF: sarà vagliata la possibilità di sviluppare un’agenda strategica e di ricerca sull’argomento allo scopo di identificare i problemi pertinenti e di formulare proposte atte a ricercare i possibili modi di affrontarli .
HYP: la strategia di ricerca e di una serie di proposte di cui si può discutere , e si possono individuare le questioni relative alla possibilità di individuare le questioni relative alla quale possono essere risolti .

EN:  there is no admission that this area is one of the largest stores of raw materials in the world and that many multinational interests are focused on this area.
REF: non si vuole ammettere che questo territorio costituisce uno dei più ricchi serbatoi di materie prime della terra e che su di esso si concentrano numerosi interessi multinazionali .
HYP: non vi è alcun motivo per cui è un paese che si occupa di una specie di dipendenza che dipendono dalla maggior parte dei paesi in via di sviluppo .

## 8. Italian-to-English translation

In [ ]:
# Only to resume data after kernel restart

import pandas as pd
from gensim.models import Word2Vec

required_resume_names = [
    "training_pairs",
    "validation_pairs",
    "test_pairs",
    "training_dataset",
    "validation_dataset",
    "english_training_sentences",
    "italian_training_sentences",
    "english_token_to_index",
    "english_index_to_token",
    "italian_token_to_index",
    "italian_index_to_token",
    "TranslationDataset",
    "DataLoader",
    "collate_batch",
    "create_lstm_model",
    "run_experiment",
    "generate_translations",
    "compute_translation_metrics",
    "tokenize",
    "MODEL_DIR",
    "RESULTS_DIR",
    "DEVICE",
]

missing_resume_names = [
    name
    for name in required_resume_names
    if name not in globals()
]

if missing_resume_names:
    raise RuntimeError(
        "Before section 8, run the setup/preparation cells "
        "listed in the note above this section. Missing names: "
        + ", ".join(missing_resume_names)
    )


BEST_LSTM_EMBEDDING_DIMENSION = 128
BEST_LSTM_HIDDEN_DIMENSION = 512
BEST_LSTM_LEARNING_RATE = 0.001
FINAL_LSTM_NUMBER_OF_EPOCHS = 30

USE_WORD2VEC_FOR_DIRECTION_COMPARISON = True
selected_model_label = "context_lstm_large_word2vec"


def require_saved_file(path, description):
    """Fail once with a clear message if a required saved output is absent."""
    if not path.exists():
        raise FileNotFoundError(
            f"Missing {description}: {path}\n"
            "Check PROJECT_ROOT and RUN_NAME in the configuration cell."
        )
    return path

embedding_comparison_path = require_saved_file(
    RESULTS_DIR / "embedding_comparison.csv",
    "embedding comparison",
)

embedding_comparison = pd.read_csv(
    embedding_comparison_path
)

selected_embedding_row = embedding_comparison.loc[
    embedding_comparison["embedding"]
    == "word2vec_initialisation"
].iloc[0]

word2vec_validation_metrics = {
    "BLEU": float(selected_embedding_row["BLEU"]),
    "METEOR": float(selected_embedding_row["METEOR"]),
}

selected_en_it_validation_metrics = (
    word2vec_validation_metrics
)


def initialise_embedding_from_word2vec(
    embedding_layer,
    token_to_index,
    word2vec_model,
):
    """Copy available Word2Vec vectors into a PyTorch embedding."""

    vocabulary_tokens = [
        token
        for token in token_to_index
        if token not in SPECIAL_TOKENS
    ]

    matched_tokens = 0

    with torch.no_grad():
        for token in vocabulary_tokens:
            if token not in word2vec_model.wv:
                continue

            vector = torch.as_tensor(
                word2vec_model.wv[token],
                dtype=embedding_layer.weight.dtype,
                device=embedding_layer.weight.device,
            )

            embedding_layer.weight[
                token_to_index[token]
            ].copy_(vector)

            matched_tokens += 1

    coverage = (
        matched_tokens / len(vocabulary_tokens)
        if vocabulary_tokens
        else 0.0
    )

    return matched_tokens, coverage

WORD2VEC_DIMENSION = BEST_LSTM_EMBEDDING_DIMENSION
WORD2VEC_WINDOW = 5
WORD2VEC_MIN_COUNT = 2
WORD2VEC_EPOCHS = 20

english_word2vec_path = (
    MODEL_DIR / "english_word2vec.model"
)
italian_word2vec_path = (
    MODEL_DIR / "italian_word2vec.model"
)

if english_word2vec_path.exists():
    english_word2vec_model = Word2Vec.load(
        str(english_word2vec_path)
    )
else:
    english_word2vec_model = Word2Vec(
        sentences=[
            tokenize(english)
            for english, _ in training_pairs
        ],
        vector_size=WORD2VEC_DIMENSION,
        window=WORD2VEC_WINDOW,
        min_count=WORD2VEC_MIN_COUNT,
        workers=1,
        sg=0,
        epochs=WORD2VEC_EPOCHS,
        seed=SEED,
    )
    english_word2vec_model.save(
        str(english_word2vec_path)
    )

if italian_word2vec_path.exists():
    italian_word2vec_model = Word2Vec.load(
        str(italian_word2vec_path)
    )
else:
    italian_word2vec_model = Word2Vec(
        sentences=[
            tokenize(italian)
            for _, italian in training_pairs
        ],
        vector_size=WORD2VEC_DIMENSION,
        window=WORD2VEC_WINDOW,
        min_count=WORD2VEC_MIN_COUNT,
        workers=1,
        sg=0,
        epochs=WORD2VEC_EPOCHS,
        seed=SEED,
    )
    italian_word2vec_model.save(
        str(italian_word2vec_path)
    )

assert (
    english_word2vec_model.vector_size
    == BEST_LSTM_EMBEDDING_DIMENSION
)
assert (
    italian_word2vec_model.vector_size
    == BEST_LSTM_EMBEDDING_DIMENSION
)

print("Resume data loaded correctly.")
print(
    "Selected EN→IT validation scores: "
    f"BLEU={word2vec_validation_metrics['BLEU']:.2f}, "
    f"METEOR={word2vec_validation_metrics['METEOR']:.2f}"
)

Resume data loaded correctly.
Selected EN→IT validation scores: BLEU=7.20, METEOR=28.25

In [ ]:
it_en_training_pairs = [
    (italian, english)
    for english, italian in training_pairs
]

it_en_validation_pairs = [
    (italian, english)
    for english, italian in validation_pairs
]

it_en_test_pairs = [
    (italian, english)
    for english, italian in test_pairs
]

it_en_training_dataset = TranslationDataset(
    it_en_training_pairs,
    italian_token_to_index,
    english_token_to_index,
)

it_en_validation_dataset = TranslationDataset(
    it_en_validation_pairs,
    italian_token_to_index,
    english_token_to_index,
)

it_en_test_dataset = TranslationDataset(
    it_en_test_pairs,
    italian_token_to_index,
    english_token_to_index,
)

it_en_training_loader = DataLoader(
    it_en_training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)

it_en_validation_loader = DataLoader(
    it_en_validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)

it_en_test_loader = DataLoader(
    it_en_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)

torch.manual_seed(SEED)

italian_to_english_model = create_lstm_model(
    source_vocabulary_size=len(italian_token_to_index),
    target_vocabulary_size=len(english_token_to_index),
    embedding_dimension=BEST_LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_LSTM_HIDDEN_DIMENSION,
)

if USE_WORD2VEC_FOR_DIRECTION_COMPARISON:
    it_en_italian_matched, it_en_italian_coverage = (
        initialise_embedding_from_word2vec(
            italian_to_english_model.encoder.embedding,
            italian_token_to_index,
            italian_word2vec_model,
        )
    )

    it_en_english_matched, it_en_english_coverage = (
        initialise_embedding_from_word2vec(
            italian_to_english_model.decoder.embedding,
            english_token_to_index,
            english_word2vec_model,
        )
    )

    assert (
        italian_to_english_model
        .encoder.embedding.weight.requires_grad
    )
    assert (
        italian_to_english_model
        .decoder.embedding.weight.requires_grad
    )

    print(
        f"Italian encoder embedding coverage: "
        f"{it_en_italian_matched:,} tokens "
        f"({it_en_italian_coverage:.1%})"
    )

    print(
        f"English decoder embedding coverage: "
        f"{it_en_english_matched:,} tokens "
        f"({it_en_english_coverage:.1%})"
    )
else:
    print("Embeddings will be learned from scratch.")


it_en_number_of_parameters = sum(
    parameter.numel()
    for parameter in italian_to_english_model.parameters()
)

print(f"\nTraining pairs: {len(it_en_training_dataset):,}")
print(f"Validation pairs: {len(it_en_validation_dataset):,}")
print(f"Test pairs: {len(it_en_test_dataset):,}")
print(f"Source language: Italian")
print(f"Target language: English")
print(f"Embedding strategy: {selected_model_label}")
print(f"Trainable parameters: {it_en_number_of_parameters:,}")
print(f"Device: {DEVICE}")

/tmp/ipykernel_2118/3114615303.py:113: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at /pytorch/torch/csrc/utils/tensor_numpy.cpp:213.)
  vector = torch.as_tensor(

Italian encoder embedding coverage: 19,996 tokens (100.0%)
English decoder embedding coverage: 19,585 tokens (97.9%)

Training pairs: 110,265
Validation pairs: 15,751
Test pairs: 31,503
Source language: Italian
Target language: English
Embedding strategy: context_lstm_large_word2vec
Trainable parameters: 19,058,208
Device: cuda

In [ ]:
IT_EN_NUMBER_OF_EPOCHS = FINAL_LSTM_NUMBER_OF_EPOCHS

IT_EN_CHECKPOINT_NAME = (
    "italian_to_english_context_lstm_"
    "e128_h512_word2vec.pt"
)

it_en_history = run_experiment(
    model=italian_to_english_model,
    training_loader=it_en_training_loader,
    validation_loader=it_en_validation_loader,
    checkpoint_name=IT_EN_CHECKPOINT_NAME,
    number_of_epochs=IT_EN_NUMBER_OF_EPOCHS,
    learning_rate=BEST_LSTM_LEARNING_RATE,
    early_stopping_patience=3,
)

Epoch 1/30 | training loss: 4.7686 | validation loss: 4.0271
Epoch 2/30 | training loss: 3.7290 | validation loss: 3.5558
Epoch 3/30 | training loss: 3.3013 | validation loss: 3.3295
Epoch 4/30 | training loss: 3.0130 | validation loss: 3.2060
Epoch 5/30 | training loss: 2.7892 | validation loss: 3.1404
Epoch 6/30 | training loss: 2.6006 | validation loss: 3.1117
Epoch 7/30 | training loss: 2.4363 | validation loss: 3.1024
Epoch 8/30 | training loss: 2.2906 | validation loss: 3.1129
Epoch 9/30 | training loss: 2.1606 | validation loss: 3.1356
Epoch 10/30 | training loss: 2.0423 | validation loss: 3.1710
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 7
Best validation loss: 3.1024
Training time: 28.38 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/italian_to_english_context_lstm_e128_h512_word2vec.pt

In [ ]:
import pandas as pd

EN_IT_TEST_RESULTS_PATH = require_saved_file(
    RESULTS_DIR / "english_to_italian_test_results.csv",
    "EN→IT test results",
)

EN_IT_TEST_TRANSLATIONS_PATH = require_saved_file(
    RESULTS_DIR / "english_to_italian_test_translations.csv",
    "EN→IT test translations",
)

en_it_test_results = pd.read_csv(
    EN_IT_TEST_RESULTS_PATH
)

en_it_test_translations_table = pd.read_csv(
    EN_IT_TEST_TRANSLATIONS_PATH
).fillna("")

en_it_test_references = [
    tokenize(text)
    for text in en_it_test_translations_table[
        "reference_italian"
    ].tolist()
]

en_it_test_hypotheses = [
    tokenize(text)
    for text in en_it_test_translations_table[
        "hypothesis_italian"
    ].tolist()
]

en_it_test_metrics = {
    "BLEU": float(en_it_test_results.iloc[0]["BLEU"]),
    "METEOR": float(en_it_test_results.iloc[0]["METEOR"]),
}

it_en_validation_references, it_en_validation_hypotheses = (
    generate_translations(
        italian_to_english_model,
        it_en_validation_loader,
        english_index_to_token,
    )
)

it_en_validation_metrics = compute_translation_metrics(
    it_en_validation_references,
    it_en_validation_hypotheses,
    target_language="english",
)


validation_direction_comparison = pd.DataFrame(
    [
        {
            "direction": "English_to_Italian",
            "BLEU": selected_en_it_validation_metrics["BLEU"],
            "METEOR": selected_en_it_validation_metrics["METEOR"],
        },
        {
            "direction": "Italian_to_English",
            "BLEU": it_en_validation_metrics["BLEU"],
            "METEOR": it_en_validation_metrics["METEOR"],
        },
    ]
)

validation_comparison_path = (
    RESULTS_DIR
    / "translation_direction_validation_comparison.csv"
)

validation_direction_comparison.to_csv(
    validation_comparison_path,
    index=False,
)


print("Validation comparison")
display(validation_direction_comparison.round(2))

it_en_inference_start = time.perf_counter()

it_en_test_references, it_en_test_hypotheses = (
    generate_translations(
        italian_to_english_model,
        it_en_test_loader,
        english_index_to_token,
    )
)

it_en_test_inference_seconds = (
    time.perf_counter() - it_en_inference_start
)


it_en_test_metrics = compute_translation_metrics(
    it_en_test_references,
    it_en_test_hypotheses,
    target_language="english",
)


it_en_test_generated_lengths = [
    len(hypothesis)
    for hypothesis in it_en_test_hypotheses
]

it_en_test_empty_percentage = (
    100
    * sum(
        length == 0
        for length in it_en_test_generated_lengths
    )
    / len(it_en_test_generated_lengths)
)

it_en_test_unique_translations = len(
    set(map(tuple, it_en_test_hypotheses))
)

it_en_test_translations_table = pd.DataFrame(
    {
        "source_italian": [
            italian
            for italian, _ in it_en_test_pairs
        ],
        "reference_english": [
            " ".join(reference)
            for reference in it_en_test_references
        ],
        "hypothesis_english": [
            " ".join(hypothesis)
            for hypothesis in it_en_test_hypotheses
        ],
        "source_length": [
            len(tokenize(italian))
            for italian, _ in it_en_test_pairs
        ],
        "reference_length": [
            len(reference)
            for reference in it_en_test_references
        ],
        "hypothesis_length": (
            it_en_test_generated_lengths
        ),
    }
)

it_en_test_translations_path = (
    RESULTS_DIR
    / "italian_to_english_test_translations.csv"
)

it_en_test_translations_table.to_csv(
    it_en_test_translations_path,
    index=False,
)

it_en_test_results = pd.DataFrame(
    [
        {
            "direction": "Italian_to_English",
            "model": selected_model_label,
            "test_examples": len(it_en_test_pairs),
            "BLEU": it_en_test_metrics["BLEU"],
            "METEOR": it_en_test_metrics["METEOR"],
            "mean_generated_length": np.mean(
                it_en_test_generated_lengths
            ),
            "empty_translations_percentage": (
                it_en_test_empty_percentage
            ),
            "unique_translations": (
                it_en_test_unique_translations
            ),
            "inference_minutes": (
                it_en_test_inference_seconds / 60
            ),
        }
    ]
)

it_en_test_results_path = (
    RESULTS_DIR
    / "italian_to_english_test_results.csv"
)

it_en_test_results.to_csv(
    it_en_test_results_path,
    index=False,
)

test_direction_comparison = pd.concat(
    [
        en_it_test_results,
        it_en_test_results,
    ],
    ignore_index=True,
)

test_comparison_path = (
    RESULTS_DIR
    / "translation_direction_test_comparison.csv"
)

test_direction_comparison.to_csv(
    test_comparison_path,
    index=False,
)

print("\nFinal test comparison")
display(
    test_direction_comparison[
        [
            "direction",
            "model",
            "test_examples",
            "BLEU",
            "METEOR",
            "mean_generated_length",
            "empty_translations_percentage",
        ]
    ].round(2)
)

bleu_difference = (
    it_en_test_metrics["BLEU"]
    - en_it_test_metrics["BLEU"]
)

meteor_difference = (
    it_en_test_metrics["METEOR"]
    - en_it_test_metrics["METEOR"]
)

print(
    "\nDifference (IT→EN minus EN→IT):"
)
print(f"BLEU: {bleu_difference:+.2f}")
print(f"METEOR: {meteor_difference:+.2f}")

print(
    f"\nSaved validation comparison: "
    f"{validation_comparison_path}"
)
print(
    f"Saved test comparison: "
    f"{test_comparison_path}"
)
print(
    f"Saved IT→EN translations: "
    f"{it_en_test_translations_path}"
)


print("\nItalian-to-English test examples:")

for i in range(5):
    print(f"\nIT:  {it_en_test_pairs[i][0]}")
    print(
        f"REF: "
        f"{' '.join(it_en_test_references[i])}"
    )
    print(
        f"HYP: "
        f"{' '.join(it_en_test_hypotheses[i]) or '<empty>'}"
    )

Validation comparison

            direction  BLEU  METEOR
0  English_to_Italian  7.20   28.25
1  Italian_to_English  9.65   34.01

Final test comparison

,direction,model,test_examples,BLEU,METEOR,mean_generated_length,empty_translations_percentage
0,English_to_Italian,context_lstm_large_word2vec,31503,7.26,28.12,23.93,0.0
1,Italian_to_English,context_lstm_large_word2vec,31503,9.60,33.94,26.48,0.0

Difference (IT→EN minus EN→IT):
BLEU: +2.33
METEOR: +5.82

Saved validation comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/translation_direction_validation_comparison.csv
Saved test comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/translation_direction_test_comparison.csv
Saved IT→EN translations: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/italian_to_english_test_translations.csv

Italian-to-English test examples:

IT:  richiesta di difesa dell'immunità parlamentare: vedasi processo verbale
REF: request for the defence of parliamentary immunity : see minutes
HYP: request for a common parliamentary immunity : see minutes

IT:  quando?
REF: when will that be ?
HYP: when will you please do that ?

IT:  naturalmente gli articoli 23 e 24 del regolamento per il coordinamento dei fondi.
REF: evidently , articles 23 and 24 of the funds coordinating regulation .
HYP: of the articles and of the regulation of the regulation on the budget of the european parliament .

IT:  sarà vagliata la possibilità di sviluppare un’agenda strategica e di ricerca sull’argomento allo scopo di identificare i problemi pertinenti e di formulare proposte atte a ricercare i possibili modi di affrontarli.
REF: the possibility of developing a strategy and research agenda on this subject will be examined , so that the relevant problems can be identified and proposals can be made for possible ways of addressing them .
HYP: it will be possible to develop the technological development of the new technologies and the use of the options to deal with the possible range of issues that are effectively and effectively , as we can be able to identify the need to be taken into account .

IT:  non si vuole ammettere che questo territorio costituisce uno dei più ricchi serbatoi di materie prime della terra e che su di esso si concentrano numerosi interessi multinazionali.
REF: there is no admission that this area is one of the largest stores of raw materials in the world and that many multinational interests are focused on this area .
HYP: it is not the intention of that power is a huge source of the oldest raw materials of the large part of the european central and the large number of people .

## 9. Character-based translation

In [ ]:
def build_character_vocabulary(sentences):
    """Build a character vocabulary using training sentences only."""
    characters = sorted(
        {
            character
            for sentence in sentences
            for character in sentence
        }
    )

    index_to_character = SPECIAL_TOKENS + characters

    character_to_index = {
        character: index
        for index, character in enumerate(index_to_character)
    }

    return character_to_index, index_to_character


english_character_to_index, english_index_to_character = (
    build_character_vocabulary(
        english_training_sentences
    )
)

italian_character_to_index, italian_index_to_character = (
    build_character_vocabulary(
        italian_training_sentences
    )
)


def encode_character_sentence(
    sentence,
    character_to_index,
):
    """Convert a sentence into character indices."""
    character_indices = [
        character_to_index.get(character, UNK_INDEX)
        for character in sentence
    ]

    return torch.tensor(
        [SOS_INDEX] + character_indices + [EOS_INDEX],
        dtype=torch.long,
    )


class CharacterTranslationDataset(Dataset):
    """Store aligned sentences encoded at character level."""

    def __init__(
        self,
        pairs,
        source_vocabulary,
        target_vocabulary,
    ):
        self.pairs = pairs
        self.source_vocabulary = source_vocabulary
        self.target_vocabulary = target_vocabulary

    def __len__(self):
        return len(self.pairs)

    def __getitem__(self, index):
        source_sentence, target_sentence = self.pairs[index]

        source = encode_character_sentence(
            source_sentence,
            self.source_vocabulary,
        )

        target = encode_character_sentence(
            target_sentence,
            self.target_vocabulary,
        )

        return source, target


character_training_dataset = CharacterTranslationDataset(
    training_pairs,
    english_character_to_index,
    italian_character_to_index,
)

character_validation_dataset = CharacterTranslationDataset(
    validation_pairs,
    english_character_to_index,
    italian_character_to_index,
)

character_test_dataset = CharacterTranslationDataset(
    test_pairs,
    english_character_to_index,
    italian_character_to_index,
)


character_training_loader = DataLoader(
    character_training_dataset,
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=collate_batch,
    generator=torch.Generator().manual_seed(SEED),
)

character_validation_loader = DataLoader(
    character_validation_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)

character_test_loader = DataLoader(
    character_test_dataset,
    batch_size=BATCH_SIZE,
    shuffle=False,
    collate_fn=collate_batch,
)

maximum_training_target_characters = max(
    len(italian)
    for _, italian in training_pairs
)

CHARACTER_MAX_DECODE_LENGTH = (
    int(np.ceil(maximum_training_target_characters * 1.10))
    + 1
)


character_source_batch, character_source_lengths, (
    character_target_batch
) = next(iter(character_training_loader))


print(
    f"English character vocabulary: "
    f"{len(english_character_to_index):,}"
)
print(
    f"Italian character vocabulary: "
    f"{len(italian_character_to_index):,}"
)

print(
    f"\nMaximum training target length: "
    f"{maximum_training_target_characters} characters"
)
print(
    f"Maximum character decoding length: "
    f"{CHARACTER_MAX_DECODE_LENGTH}"
)

print(f"\nTraining pairs: {len(character_training_dataset):,}")
print(
    f"Validation pairs: "
    f"{len(character_validation_dataset):,}"
)
print(f"Test pairs: {len(character_test_dataset):,}")

print(
    f"Source batch shape: "
    f"{character_source_batch.shape}"
)
print(
    f"Target batch shape: "
    f"{character_target_batch.shape}"
)
print(f"Device: {DEVICE}")

English character vocabulary: 140
Italian character vocabulary: 136

Maximum training target length: 343 characters
Maximum character decoding length: 379

Training pairs: 110,265
Validation pairs: 15,751
Test pairs: 31,503
Source batch shape: torch.Size([128, 235])
Target batch shape: torch.Size([128, 240])
Device: cuda

In [ ]:
CHARACTER_NUMBER_OF_EPOCHS = FINAL_LSTM_NUMBER_OF_EPOCHS
CHARACTER_LEARNING_RATE = BEST_LSTM_LEARNING_RATE

torch.manual_seed(SEED)

character_lstm_model = create_lstm_model(
    source_vocabulary_size=len(
        english_character_to_index
    ),
    target_vocabulary_size=len(
        italian_character_to_index
    ),
    embedding_dimension=BEST_LSTM_EMBEDDING_DIMENSION,
    hidden_dimension=BEST_LSTM_HIDDEN_DIMENSION,
)


character_number_of_parameters = sum(
    parameter.numel()
    for parameter in character_lstm_model.parameters()
)

print(
    f"Character model parameters: "
    f"{character_number_of_parameters:,}"
)
print(
    f"Embedding dimension: "
    f"{BEST_LSTM_EMBEDDING_DIMENSION}"
)
print(
    f"Hidden dimension: "
    f"{BEST_LSTM_HIDDEN_DIMENSION}"
)
print(f"Learning rate: {CHARACTER_LEARNING_RATE}")
print(f"Maximum epochs: {CHARACTER_NUMBER_OF_EPOCHS}")


character_lstm_history = run_experiment(
    model=character_lstm_model,
    training_loader=character_training_loader,
    validation_loader=character_validation_loader,
    checkpoint_name=(
        "english_to_italian_character_lstm_e128_h512.pt"
    ),
    number_of_epochs=CHARACTER_NUMBER_OF_EPOCHS,
    learning_rate=CHARACTER_LEARNING_RATE,
    early_stopping_patience=3,
)

Character model parameters: 3,783,304
Embedding dimension: 128
Hidden dimension: 512
Learning rate: 0.001
Maximum epochs: 30
Epoch 1/30 | training loss: 1.5503 | validation loss: 1.2106
Epoch 2/30 | training loss: 1.1184 | validation loss: 1.0528
Epoch 3/30 | training loss: 1.0102 | validation loss: 0.9776
Epoch 4/30 | training loss: 0.9497 | validation loss: 0.9333
Epoch 5/30 | training loss: 0.9075 | validation loss: 0.9011
Epoch 6/30 | training loss: 0.8754 | validation loss: 0.8767
Epoch 7/30 | training loss: 0.8500 | validation loss: 0.8600
Epoch 8/30 | training loss: 0.8292 | validation loss: 0.8474
Epoch 9/30 | training loss: 0.8114 | validation loss: 0.8374
Epoch 10/30 | training loss: 0.7962 | validation loss: 0.8304
Epoch 11/30 | training loss: 0.7828 | validation loss: 0.8235
Epoch 12/30 | training loss: 0.7709 | validation loss: 0.8211
Epoch 13/30 | training loss: 0.7602 | validation loss: 0.8189
Epoch 14/30 | training loss: 0.7504 | validation loss: 0.8134
Epoch 15/30 | training loss: 0.7413 | validation loss: 0.8124
Epoch 16/30 | training loss: 0.7328 | validation loss: 0.8138
Epoch 17/30 | training loss: 0.7250 | validation loss: 0.8122
Epoch 18/30 | training loss: 0.7178 | validation loss: 0.8117
Epoch 19/30 | training loss: 0.7109 | validation loss: 0.8153
Epoch 20/30 | training loss: 0.7044 | validation loss: 0.8135
Epoch 21/30 | training loss: 0.6985 | validation loss: 0.8158
Early stopping: validation loss did not improve for 3 epochs.
Best epoch: 18
Best validation loss: 0.8117
Training time: 85.74 minutes
Checkpoint: /content/drive/MyDrive/English-Italian-Machine-Translation-/models/task3/gpu_punctuation_final/english_to_italian_character_lstm_e128_h512.pt

In [ ]:
def character_indices_to_text(
    indices,
    index_to_character,
):
    """Convert generated indices back into a sentence."""
    characters = []

    for index in indices:
        index = int(index)

        if index == EOS_INDEX:
            break

        if index in (PAD_INDEX, SOS_INDEX):
            continue

        if index == UNK_INDEX:
            characters.append("�")
        else:
            characters.append(
                index_to_character[index]
            )

    return "".join(characters)


@torch.no_grad()
def generate_character_translations(
    model,
    data_loader,
    target_index_to_character,
    max_decode_length,
):
    """Generate complete target sentences character by character."""
    model.eval()

    hypotheses = []

    for source, source_lengths, _ in data_loader:
        source = source.to(DEVICE)

        context = model.encoder(
            source,
            source_lengths,
        )
        state = context

        current_token = torch.full(
            (source.size(0), 1),
            SOS_INDEX,
            dtype=torch.long,
            device=DEVICE,
        )

        generated_indices = []

        finished = torch.zeros(
            source.size(0),
            dtype=torch.bool,
            device=DEVICE,
        )

        for _ in range(max_decode_length):
            logits, state = model.decoder(
                current_token,
                state,
                context,
            )

            step_logits = logits[:, -1].clone()
            step_logits[
                :,
                [PAD_INDEX, SOS_INDEX],
            ] = float("-inf")

            next_token = step_logits.argmax(dim=-1)

            next_token = torch.where(
                finished,
                torch.full_like(
                    next_token,
                    EOS_INDEX,
                ),
                next_token,
            )

            generated_indices.append(
                next_token.cpu()
            )

            finished |= next_token.eq(EOS_INDEX)
            current_token = next_token.unsqueeze(1)

            if finished.all():
                break

        generated_indices = torch.stack(
            generated_indices,
            dim=1,
        )

        hypotheses.extend(
            character_indices_to_text(
                sequence,
                target_index_to_character,
            )
            for sequence in generated_indices
        )

    references = [
        target_sentence
        for _, target_sentence in data_loader.dataset.pairs
    ]

    assert len(references) == len(hypotheses)

    return references, hypotheses


def tokenize_generated_texts(texts):
    """Apply the original word tokenizer before evaluation."""
    return [
        tokenize(text)
        for text in texts
    ]

character_validation_reference_texts, (
    character_validation_hypothesis_texts
) = generate_character_translations(
    character_lstm_model,
    character_validation_loader,
    italian_index_to_character,
    CHARACTER_MAX_DECODE_LENGTH,
)

character_validation_references = (
    tokenize_generated_texts(
        character_validation_reference_texts
    )
)

character_validation_hypotheses = (
    tokenize_generated_texts(
        character_validation_hypothesis_texts
    )
)

character_validation_metrics = (
    compute_translation_metrics(
        character_validation_references,
        character_validation_hypotheses,
        target_language="italian",
    )
)

character_word_validation_comparison = pd.DataFrame(
    [
        {
            "model": "word_lstm_large_word2vec",
            "representation": "word",
            "embedding": "word2vec_initialisation",
            "BLEU": (
                selected_en_it_validation_metrics["BLEU"]
            ),
            "METEOR": (
                selected_en_it_validation_metrics["METEOR"]
            ),
        },
        {
            "model": "character_lstm",
            "representation": "character",
            "embedding": "learned_from_scratch",
            "BLEU": (
                character_validation_metrics["BLEU"]
            ),
            "METEOR": (
                character_validation_metrics["METEOR"]
            ),
        },
    ]
)


character_validation_comparison_path = (
    RESULTS_DIR
    / "character_word_validation_comparison.csv"
)

character_word_validation_comparison.to_csv(
    character_validation_comparison_path,
    index=False,
)


print("Validation comparison")
display(
    character_word_validation_comparison.round(2)
)

character_test_start_time = time.perf_counter()

character_test_reference_texts, (
    character_test_hypothesis_texts
) = generate_character_translations(
    character_lstm_model,
    character_test_loader,
    italian_index_to_character,
    CHARACTER_MAX_DECODE_LENGTH,
)

character_test_inference_seconds = (
    time.perf_counter()
    - character_test_start_time
)


character_test_references = tokenize_generated_texts(
    character_test_reference_texts
)

character_test_hypotheses = tokenize_generated_texts(
    character_test_hypothesis_texts
)

character_test_metrics = compute_translation_metrics(
    character_test_references,
    character_test_hypotheses,
    target_language="italian",
)


character_test_word_lengths = [
    len(hypothesis)
    for hypothesis in character_test_hypotheses
]

character_test_character_lengths = [
    len(hypothesis)
    for hypothesis in character_test_hypothesis_texts
]

character_test_empty_percentage = (
    100
    * sum(
        not hypothesis.strip()
        for hypothesis in character_test_hypothesis_texts
    )
    / len(character_test_hypothesis_texts)
)

character_test_unique_translations = len(
    set(character_test_hypothesis_texts)
)


character_test_translations_table = pd.DataFrame(
    {
        "source_english": [
            english
            for english, _ in test_pairs
        ],
        "reference_italian": (
            character_test_reference_texts
        ),
        "hypothesis_italian": (
            character_test_hypothesis_texts
        ),
        "source_word_length": [
            len(tokenize(english))
            for english, _ in test_pairs
        ],
        "reference_word_length": [
            len(reference)
            for reference in character_test_references
        ],
        "hypothesis_word_length": (
            character_test_word_lengths
        ),
        "reference_character_length": [
            len(reference)
            for reference in character_test_reference_texts
        ],
        "hypothesis_character_length": (
            character_test_character_lengths
        ),
    }
)

character_test_translations_path = (
    RESULTS_DIR
    / "english_to_italian_character_test_translations.csv"
)

character_test_translations_table.to_csv(
    character_test_translations_path,
    index=False,
)


character_test_results = pd.DataFrame(
    [
        {
            "direction": "English_to_Italian",
            "model": "character_lstm",
            "test_examples": len(test_pairs),
            "BLEU": character_test_metrics["BLEU"],
            "METEOR": character_test_metrics["METEOR"],
            "mean_generated_length": np.mean(
                character_test_word_lengths
            ),
            "empty_translations_percentage": (
                character_test_empty_percentage
            ),
            "unique_translations": (
                character_test_unique_translations
            ),
            "inference_minutes": (
                character_test_inference_seconds / 60
            ),
        }
    ]
)

character_test_results_path = (
    RESULTS_DIR
    / "english_to_italian_character_test_results.csv"
)

character_test_results.to_csv(
    character_test_results_path,
    index=False,
)

character_word_test_comparison = pd.concat(
    [
        en_it_test_results,
        character_test_results,
    ],
    ignore_index=True,
)

character_test_comparison_path = (
    RESULTS_DIR
    / "character_word_test_comparison.csv"
)

character_word_test_comparison.to_csv(
    character_test_comparison_path,
    index=False,
)


print("\nFinal test comparison")
display(
    character_word_test_comparison[
        [
            "model",
            "test_examples",
            "BLEU",
            "METEOR",
            "mean_generated_length",
            "empty_translations_percentage",
            "unique_translations",
            "inference_minutes",
        ]
    ].round(2)
)


word_test_bleu = float(
    en_it_test_results.iloc[0]["BLEU"]
)
word_test_meteor = float(
    en_it_test_results.iloc[0]["METEOR"]
)

print("\nDifference (character minus final word model)")
print(
    f"BLEU: "
    f"{character_test_metrics['BLEU'] - word_test_bleu:+.2f}"
)
print(
    f"METEOR: "
    f"{character_test_metrics['METEOR'] - word_test_meteor:+.2f}"
)

print(
    f"\nMean generated characters: "
    f"{np.mean(character_test_character_lengths):.2f}"
)
print(
    f"Saved validation comparison: "
    f"{character_validation_comparison_path}"
)
print(
    f"Saved test comparison: "
    f"{character_test_comparison_path}"
)
print(
    f"Saved character translations: "
    f"{character_test_translations_path}"
)


print("\nCharacter-model test examples:")

for i in range(5):
    print(f"\nEN:  {test_pairs[i][0]}")
    print(
        f"REF: "
        f"{character_test_reference_texts[i]}"
    )
    print(
        f"HYP: "
        f"{character_test_hypothesis_texts[i] or '<empty>'}"
    )

Validation comparison

,model,representation,embedding,BLEU,METEOR
0,word_lstm_large_word2vec,word,word2vec_initialisation,7.20,28.25
1,character_lstm,character,learned_from_scratch,3.96,20.02

Final test comparison

,model,test_examples,BLEU,METEOR,mean_generated_length,empty_translations_percentage,unique_translations,inference_minutes
0,context_lstm_large_word2vec,31503,7.26,28.12,23.93,0.0,30792,0.41
1,character_lstm,31503,3.86,19.83,25.46,0.0,30913,1.44

Difference (character minus final word model)
BLEU: -3.40
METEOR: -8.29

Mean generated characters: 153.55
Saved validation comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/character_word_validation_comparison.csv
Saved test comparison: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/character_word_test_comparison.csv
Saved character translations: /content/drive/MyDrive/English-Italian-Machine-Translation-/results/task3_outputs/gpu_punctuation_final/english_to_italian_character_test_translations.csv

Character-model test examples:

EN:  request for the defence of parliamentary immunity: see minutes
REF: richiesta di difesa dell'immunità parlamentare: vedasi processo verbale
HYP: richiesta di difesa della parola della parola della parizzazione dell' ammissivazione dell'immunità della parola.

EN:  when will that be?
REF: quando?
HYP: quale sarà possibile conservare?

EN:  evidently, articles 23 and 24 of the funds coordinating regulation.
REF: naturalmente gli articoli 23 e 24 del regolamento per il coordinamento dei fondi.
HYP: tra controllo, concordato da parte dell'articolo 13 e 18 del regolamento del regolamento.

EN:  the possibility of developing a strategy and research agenda on this subject will be examined, so that the relevant problems can be identified and proposals can be made for possible ways of addressing them.
REF: sarà vagliata la possibilità di sviluppare un’agenda strategica e di ricerca sull’argomento allo scopo di identificare i problemi pertinenti e di formulare proposte atte a ricercare i possibili modi di affrontarli.
HYP: la possibilità di risolvere la risoluzione di controllo dei programmi possibile per i programmi di conservazione delle relazioni con la risoluzione di cui disponiamo di una strategia possibile per la ricerca e sviluppo della relazione.

EN:  there is no admission that this area is one of the largest stores of raw materials in the world and that many multinational interests are focused on this area.
REF: non si vuole ammettere che questo territorio costituisce uno dei più ricchi serbatoi di materie prime della terra e che su di esso si concentrano numerosi interessi multinazionali.
HYP: non è ancora una volta in questo campo e che la maggior parte delle mani dell'unione europea è uno dei più poveri e i porti di tale problema.